import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { Category } from "@prisma/client";
import { ExamClient } from "@/app/(dashboard)/exam/[year]/exam-client";

const FALLBACK_TIMED_QUESTIONS = [
  {
    id: "timed-1",
    question: "اشترى رجل وزوجته وأبناؤه الثلاثة تذاكر سفر، وهناك خصم ٥٠٪ على تذكرة الطفل. إذا كان إجمالي ما دفعوه ١٤٠٠ ريال، فما سعر تذكرة البالغ؟",
    options: ["٢٠٠", "٣٠٠", "٤٠٠", "١٠٠"],
    correctAnswer: 2,
    explanation: "بفرض سعر البالغ = س: \\( ٢س + ٣(٠.٥س) = ١٤٠٠ \\Rightarrow ٣.٥س = ١٤٠٠ \\Rightarrow س = ٤٠٠ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-2",
    question: "كان متوسط درجات طلاب مدرسة ٨٠، وهناك طالب غائب، وعند إعادة اختباره حصل على ٣٠ درجة فأصبح متوسط درجات طلاب المدرسة ٨٥. ما عدد طلاب المدرسة؟",
    options: ["٥", "٦", "٨", "١٠"],
    correctAnswer: 1,
    explanation: "بفرض عدد الطلاب = ن: \\( \\frac{٨٠ن+٣٠}{ن} = ٨٥ \\Rightarrow ٣٠=٥ن \\Rightarrow ن=٦ \\)",
    difficulty: "HARD",
  },
  {
    id: "timed-3",
    question: "ما أكبر عدد مكوّن من الأرقام (١، ٢، ٣، ٥) بحيث يكون أكبر من ١٠٠٠ بدون تكرار الرقم؟",
    options: ["٥٣١٢", "٣٥٢١", "٥٢٣١", "٥٣٢١"],
    correctAnswer: 3,
    explanation: "أكبر عدد رباعي من هذه الأرقام هو ترتيبها تنازلياً: ٥٣٢١.",
    difficulty: "EASY",
  },
  {
    id: "timed-4",
    question: "مربع محيطه ٢٠، قارن بين مساحة المربع و٢٠م².",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 0,
    explanation: "طول الضلع \\( = ٢٠\\div٤=٥ \\)، والمساحة \\( = ٥^{2}=٢٥ \\)م² وهي أكبر من ٢٠م².",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-5",
    question: "خمسة منازل، في كل منزل خمسة أقفاص، في كل قفص خمسة عصافير، وكل عصفور يأكل خمسة حبوب قمح. فكم عدد حبوب القمح التي يأكلونها؟",
    options: ["١٢٥", "٢٢٥", "٦٢٥", "٥٠"],
    correctAnswer: 2,
    explanation: "\\( ٥ \\times ٥ \\times ٥ \\times ٥ = ٦٢٥ \\) حبة.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-6",
    question: "باعت مكتبة ثمن \\( \\left(\\frac{١}{٨}\\right) \\) عدد كتب التاريخ، ثم اشترت ١٠ كتب جديدة فأصبح عدد الكتب ٥٢. أوجد عدد الكتب الأصلي.",
    options: ["٣٢", "٤٨", "٥٤", "٦٢"],
    correctAnswer: 1,
    explanation: "\\( س − \\frac{س}{٨} + ١٠ = ٥٢ \\Rightarrow \\frac{٧}{٨}س = ٤٢ \\Rightarrow س = ٤٨ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-7",
    question: "احسب مساحة الأوجه لمتوازي مستطيلات قياساته ٢، ٢، ٥.",
    options: ["٢٠", "٢٤", "٤٨", "٥٠"],
    correctAnswer: 2,
    explanation: "مساحة الأوجه \\( = ٢(٢\\times٢+٢\\times٥+٢\\times٥) = ٢\\times٢٤ = ٤٨ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-8",
    question: "في مخطط دائري، عدد من يفضلون فصل الربيع = ٢٠ وعدد من يفضلون فصل الشتاء = ٧٠. أوجد النسبة بين الذين يفضلون الربيع إلى الذين يفضلون الشتاء.",
    options: ["\\( \\frac{٧}{٢} \\)", "\\( \\frac{٢}{٧} \\)", "\\( \\frac{٧}{٩} \\)", "\\( \\frac{٢}{٩} \\)"],
    correctAnswer: 1,
    explanation: "النسبة \\( = ٢٠:٧٠ = ٢:٧ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-9",
    question: "إذا كان مع شخص ٤٠٠٠ ريال، فإن مقدار الزكاة يساوي؟",
    options: ["١٠٠", "٢٠٠٠", "٣٠٠٠", "٤٠٠٠"],
    correctAnswer: 0,
    explanation: "الزكاة = ٢.٥٪ من ٤٠٠٠ = ١٠٠ ريال.",
    difficulty: "EASY",
  },
  {
    id: "timed-10",
    question: "خمسة أمثال \\( \\left(\\frac{١}{٧}\\right) \\) س يساوي ٣٠، فما قيمة س؟",
    options: ["١٨", "٢٥", "٣٥", "٤٢"],
    correctAnswer: 3,
    explanation: "\\( ٥\\times\\frac{١}{٧}س = ٣٠ \\Rightarrow \\frac{٥}{٧}س = ٣٠ \\Rightarrow س = ٤٢ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-11",
    question: "في محطة سيارات: السيارة الأولى تكلفتها ١١٠٠ ريال وأجرة سائقها ٦٠٠ (مسافتها ١٠٠٠م)، الثانية تكلفتها ١١٥٠ وأجرة سائقها ٤٠٠ (مسافتها ١٨٠٠٠م). إذا كان لتر الوقود يباع بـ٥ ريال، فأي السيارتين أكثر توفيراً للوقود؟",
    options: ["الأولى", "الثانية", "متساويتان", "لا يمكن التحديد"],
    correctAnswer: 1,
    explanation: "الأولى: تكلفة وقود \\( =٥٠٠ \\) ريال \\( =١٠٠ \\) لتر لمسافة ١٠٠٠م \\( \\Leftarrow ١٠ \\) م/لتر. الثانية: تكلفة وقود \\( =٧٥٠=١٥٠ \\) لتر لمسافة ١٨٠٠٠م \\( \\Leftarrow ١٢٠ \\) م/لتر، وهي الأكثر كفاءة.",
    difficulty: "HARD",
  },
  {
    id: "timed-12",
    question: "قارن بين: عدد الدقائق في \\( \\left(\\frac{١}{٣}\\right) \\) ساعة، و\\( ٣\\times٢^{2} \\)",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 0,
    explanation: "ثلث الساعة = ٢٠ دقيقة، و\\( ٣\\times٤=١٢ \\)، فالقيمة الأولى (٢٠) أكبر.",
    difficulty: "EASY",
  },
  {
    id: "timed-13",
    question: "خمسة أمثال عدد مطروح منه ٢ يساوي ١٨، فما هذا العدد؟",
    options: ["٣", "٤", "٥", "٦"],
    correctAnswer: 1,
    explanation: "\\( ٥س − ٢ = ١٨ \\Rightarrow ٥س = ٢٠ \\Rightarrow س = ٤ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-14",
    question: "أوجد المنوال للأرقام التالية: ١، ٥، ٣، ٤، ١، ٦، ٥، ٣، ١",
    options: ["١", "٣", "٥", "٦"],
    correctAnswer: 0,
    explanation: "الرقم ١ تكرر ٣ مرات وهو الأكثر تكراراً، فهو المنوال.",
    difficulty: "EASY",
  },
  {
    id: "timed-15",
    question: "إذا كانت ١٠٠ هللة = ١ ريال، فكم تساوي ٤ هللة؟",
    options: ["٠.٠٠٤", "٠.٠٤", "٠.٤", "٤"],
    correctAnswer: 1,
    explanation: "٤ هللة \\( = \\frac{٤}{١٠٠} = ٠.٠٤ \\) ريال.",
    difficulty: "EASY",
  },
  {
    id: "timed-16",
    question: "ما العدد الذي ثلثه يساوي \\( \\frac{١٠}{١٥} \\)؟",
    options: ["١", "٢", "٣", "٤"],
    correctAnswer: 1,
    explanation: "\\( \\frac{س}{٣} = \\frac{١٠}{١٥} = \\frac{٢}{٣} \\Rightarrow س = ٢ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-17",
    question: "ما ناتج \\( \\frac{١٠^{5} − ١٠^{4}}{٩} \\) ؟",
    options: ["١٠", "١٠٠٠", "٩٠٠٠", "١٠٠٠٠"],
    correctAnswer: 3,
    explanation: "\\( \\frac{١٠٠٠٠٠ − ١٠٠٠٠}{٩} = \\frac{٩٠٠٠٠}{٩} = ١٠٠٠٠ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-18",
    question: "لدى محمد ورقتين على شكل مربع: الأول محيطه ١٢، والثاني محيطه ١٦. قارن بين مساحة المربع الأول ومساحة المربع الثاني.",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 1,
    explanation: "ضلع الأول \\( =٣ \\)، مساحته \\( =٩ \\). ضلع الثاني \\( =٤ \\)، مساحته \\( =١٦ \\). فالثانية أكبر.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-19",
    question: "خمس أعداد، متوسط أول ٣ أعداد منها = ١٠، ومتوسط آخر عددين = ١٥. كم متوسط الخمسة أعداد؟",
    options: ["١٢", "١٢.٥", "١٣", "١٣.٥"],
    correctAnswer: 0,
    explanation: "مجموع الأول \\( =٣٠ \\)، ومجموع الآخرين \\( =٣٠ \\)، المجموع الكلي \\( =٦٠ \\)، والمتوسط \\( =٦٠\\div٥=١٢ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-20",
    question: "اشترى خالد سلكاً طوله ١٥٠ سم، وكل ٢سم منه ثقله ٣ جرام. إذا أضاف ثقلاً فأصبح طول السلك ١٦٠سم، فما كتلة الثقل المضاف؟",
    options: ["٥", "١٠", "١٥", "٢٠"],
    correctAnswer: 2,
    explanation: "الزيادة \\( = ١٠ \\)سم، وكتلتها \\( = \\left(\\frac{١٠}{٢}\\right)\\times٣ = ١٥ \\) جرام.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-21",
    question: "إذا كانت المسافة بين بيت يوسف وصديقه ٨ كيلومتر، فكم طول الطريق بالأمتار؟",
    options: ["٨٠", "٨٠٠", "٨٠٠٠", "٨٠٠٠٠"],
    correctAnswer: 2,
    explanation: "١كم = ١٠٠٠م، فـ٨كم = ٨٠٠٠م.",
    difficulty: "EASY",
  },
  {
    id: "timed-22",
    question: "شخص حل ٦٠٪ من الاختبار، وكانت هذه النسبة تمثل ٣٠ سؤالاً. أوجد عدد أسئلة الاختبار.",
    options: ["٤٠", "٥٠", "٦٠", "٩٠"],
    correctAnswer: 1,
    explanation: "\\( ٠.٦س = ٣٠ \\Rightarrow س = ٥٠ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-23",
    question: "ثامر يدفع ريالين لكل ساعة أو جزء منها في موقف سيارات. إذا وقف من الساعة ٨:٠٥ وتحرك الساعة ١١:٤٥، فكم ريال سيدفع؟",
    options: ["٦", "٨", "٩", "١٠"],
    correctAnswer: 1,
    explanation: "المدة = ٣ ساعات و٤٠ دقيقة، تُحسب كـ٤ ساعات كاملة، فالدفع \\( = ٤\\times٢ = ٨ \\) ريالات.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-24",
    question: "مستطيل عرضه ٢ص ومحيطه (٦ص + ٢س)، فكم يساوي طوله؟",
    options: ["ص − س", "ص + س", "ص س", "س ص"],
    correctAnswer: 1,
    explanation: "\\( ٢(ل+ع)=٦ص+٢س \\Rightarrow ل+٢ص=٣ص+س \\Rightarrow ل=ص+س \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-25",
    question: "قارن بين: ثمن الساعة \\( \\left(\\frac{١}{٨}\\right) \\) وسدس الساعة \\( \\left(\\frac{١}{٦}\\right) \\)",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 1,
    explanation: "ثمن الساعة = ٧.٥ دقيقة، وسدس الساعة = ١٠ دقائق، فالثانية أكبر.",
    difficulty: "EASY",
  },
  {
    id: "timed-26",
    question: "ما ناتج \\( ٨ \\times ٦ + ٥ + ٥ \\) ؟",
    options: ["٤٠", "٥٠", "٥٨", "١٢٨"],
    correctAnswer: 2,
    explanation: "حسب ترتيب العمليات: \\( ٨\\times٦=٤٨ \\)، ثم \\( ٤٨+٥+٥=٥٨ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-27",
    question: "ربع عدد = ٦٠٠٠، فما نصف ثلث هذا العدد؟",
    options: ["٤٠٠٠", "٥٠٠٠", "٦٠٠٠", "٩٠٠٠"],
    correctAnswer: 0,
    explanation: "العدد \\( = ٦٠٠٠\\times٤ = ٢٤٠٠٠ \\). ثلثه \\( = ٨٠٠٠ \\)، ونصفه \\( = ٤٠٠٠ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-28",
    question: "أراد علي أن يطبع كتاباً، فإذا طبعت الطابعة ٢٥٨ رقماً في ترقيم الصفحات، فكم عدد صفحات الكتاب؟",
    options: ["١٢٠", "١٢٢", "١٢٤", "١٢٦"],
    correctAnswer: 1,
    explanation: "صفحات ١-٩: ٩ أرقام. صفحات ١٠-٩٩: ٩٠ صفحة \\( \\times٢=١٨٠ \\) رقماً (المجموع ١٨٩). المتبقي \\( =٦٩ \\) رقماً \\( \\div٣=٢٣ \\) صفحة. الإجمالي \\( =٩٩+٢٣=١٢٢ \\) صفحة.",
    difficulty: "HARD",
  },
  {
    id: "timed-29",
    question: "الفرق بين عمر خالد وأحمد = ١٨ عاماً، وعمر خالد ربع عمر أحمد. كم عمر خالد؟",
    options: ["٤", "٥", "٦", "٩"],
    correctAnswer: 2,
    explanation: "أحمد \\( =٤ \\) خالد، فـ\\( ٤ \\) خالد \\( − \\) خالد \\( =١٨ \\Rightarrow ٣ \\) خالد \\( =١٨ \\Rightarrow \\) خالد \\( =٦ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-30",
    question: "يستغرق محمد بالسير من البيت إلى المدرسة ٦٠ دقيقة، وبالسيارة ٩ دقائق. إذا مشى لمدة ٢٠ دقيقة ثم أكمل طريقه بالسيارة، فما الزمن الكلي بالدقائق؟",
    options: ["٢٠", "٢٤", "٢٦", "٣٠"],
    correctAnswer: 2,
    explanation: "بعد ٢٠ دقيقة يكون قطع \\( \\frac{١}{٣} \\) المسافة سيراً، يبقى \\( \\frac{٢}{٣} \\) بالسيارة \\( = \\left(\\frac{٢}{٣}\\right)\\times٩=٦ \\) دقائق. الإجمالي \\( =٢٠+٦=٢٦ \\) دقيقة.",
    difficulty: "HARD",
  },
  {
    id: "timed-31",
    question: "أوجد الحد الناقص في المتتابعة: ١، ٦، ...، ١٦، ٢١",
    options: ["٨", "١٠", "١١", "٢٥"],
    correctAnswer: 2,
    explanation: "المتتابعة حسابية بفرق ٥: ١،٦،١١،١٦،٢١.",
    difficulty: "EASY",
  },
  {
    id: "timed-32",
    question: "عدد مكوّن من رقمين آحاده يقل عن عشراته بمقدار ٢، وخمسة أمثال مجموع رقميه مقسومة على ١٠ يساوي ٧. ما هذا العدد؟",
    options: ["٦١", "٦٥", "٨١", "٨٦"],
    correctAnswer: 3,
    explanation: "بفرض العشرات=أ والآحاد=أ−٢: \\( \\frac{٥(٢أ−٢)}{١٠}=٧ \\Rightarrow أ−١=٧ \\Rightarrow أ=٨ \\)، الآحاد \\( =٦ \\)، العدد \\( =٨٦ \\)",
    difficulty: "HARD",
  },
  {
    id: "timed-33",
    question: "رسمت هدى مستطيلاً عرضه ١٢٠ سم وطوله ٦٠ سم، فإذا أرادت تغطيته بورق مربع طول ضلعه ٢٠ سم، فكم عدد الأوراق التي ستحتاجها؟",
    options: ["١٤", "١٥", "١٨", "١٩"],
    correctAnswer: 2,
    explanation: "مساحة المستطيل \\( =١٢٠\\times٦٠=٧٢٠٠ \\)سم²، مساحة الورقة \\( =٢٠\\times٢٠=٤٠٠ \\)سم²، العدد \\( =٧٢٠٠\\div٤٠٠=١٨ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-34",
    question: "ما العدد الذي يقبل القسمة على مجموع أرقامه، من بين: ١٥، ١٦، ١٧، ١٨؟",
    options: ["١٥", "١٦", "١٧", "١٨"],
    correctAnswer: 3,
    explanation: "مجموع أرقام ١٨=٩، و\\( ١٨\\div٩=٢ \\) (عدد صحيح)، بينما الخيارات الأخرى لا تقبل القسمة على مجموع أرقامها.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-35",
    question: "متوسط مشاهدة شخص للتلفاز عام ٢٠١١ = ١٤٧٠ دقيقة. أوجد متوسط المشاهدة عام ٢٠١٢ تقريباً إذا زاد بنسبة ٧٪ عن عام ٢٠١١.",
    options: ["١٠٦٣", "١٥٤٠", "١٥٦٣", "١٥٧٣"],
    correctAnswer: 3,
    explanation: "\\( ١٤٧٠ \\times ١.٠٧ \\approx ١٥٧٣ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-36",
    question: "أوجد قيمة: ١ + ٢ + ٣ + ٤ + ٥ + ٦ + ٦ + ٥ + ٤ + ٣ + ٢ + ١",
    options: ["\\( ٧\\times٥ \\)", "\\( ٦\\times٧ \\)", "\\( ٨\\times٩ \\)", "\\( ٨\\times٧ \\)"],
    correctAnswer: 1,
    explanation: "المجموع \\( = ٢\\times(١+٢+٣+٤+٥+٦) = ٢\\times٢١ = ٤٢ = ٦\\times٧ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-37",
    question: "كان سعر السهم ١٥٠ في عام ١٤٣٣، فإذا أصبح سعره ٩٠ في عام ١٤٣٤، فكم نسبة خسارة السهم؟",
    options: ["٢٥٪", "٣٥٪", "٤٠٪", "٦٠٪"],
    correctAnswer: 2,
    explanation: "الخسارة = ٦٠ من أصل ١٥٠ = ٤٠٪.",
    difficulty: "EASY",
  },
  {
    id: "timed-38",
    question: "أوجد قيمة التالي: ١٨ − ٢جـ + ١٢ − ٥جـ + ١٠ − جـ = ....",
    options: ["\\( ٨جـ − ٥ \\)", "\\( ٤٠ − ٥جـ \\)", "\\( ٨(٥ − جـ) \\)", "\\( ٤(٥ − جـ) \\)"],
    correctAnswer: 2,
    explanation: "بجمع الثوابت (١٨+١٢+١٠=٤٠) وحدود جـ \\( (−٢جـ−٥جـ−جـ=−٨جـ) \\): الناتج \\( =٤٠−٨جـ=٨(٥−جـ) \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-39",
    question: "في الشكل المجاور مثلث متطابق الأضلاع بأضلاع (٥س−١) و(٣س+٥)، قارن بين محيط المثلث و٤٢.",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 2,
    explanation: "بما أن الأضلاع متساوية: \\( ٥س−١=٣س+٥ \\Rightarrow س=٣ \\)، الضلع \\( =١٤ \\)، المحيط \\( =٤٢ \\)، فهما متساويان.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-40",
    question: "إذا علمت أن ٣ قطع ذهبية = ١٠ قطع فضية + قطعة ذهبية، فقارن بين قطعة ذهبية واحدة و٥ قطع فضية.",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 2,
    explanation: "\\( ٣ذ=١٠ف+ذ \\Rightarrow ٢ذ=١٠ف \\Rightarrow ذ=٥ف \\)، فهما متساويتان.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-41",
    question: "يستطيع محمد شراء ٢٥ كتاباً، فإذا خُصم ريالان للكتاب فيستطيع شراء ٥ كتب إضافية بنفس المبلغ. كم كان معه من المال؟",
    options: ["٣٠٠", "٣١٠", "٣٤٠", "٣٦٠"],
    correctAnswer: 0,
    explanation: "بفرض السعر=ع والمبلغ=٢٥ع: \\( \\frac{٢٥ع}{ع−٢}=٣٠ \\Rightarrow ٢٥ع=٣٠ع−٦٠ \\Rightarrow ع=١٢ \\)، المبلغ \\( =٢٥\\times١٢=٣٠٠ \\)",
    difficulty: "HARD",
  },
  {
    id: "timed-42",
    question: "ما الفرق بين أصغر عدد فردي مكوّن من ٣ أرقام وأكبر عدد زوجي مكوّن من رقمين؟",
    options: ["٢", "٣", "٥", "٧"],
    correctAnswer: 1,
    explanation: "أصغر عدد فردي من ٣ أرقام=١٠١، وأكبر عدد زوجي من رقمين=٩٨، والفرق \\( =١٠١−٩٨=٣ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-43",
    question: "قارن بين \\( \\frac{١٠٠٠}{٩٩٩} \\) و\\( \\frac{١٠٠}{٩٩} \\)",
    options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"],
    correctAnswer: 1,
    explanation: "\\( \\frac{١٠٠٠}{٩٩٩} \\approx ١.٠٠١ \\)، و\\( \\frac{١٠٠}{٩٩} \\approx ١.٠١٠١ \\)، فالقيمة الثانية أكبر.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-44",
    question: "أوجد مجموع: ١ − ٢ + ٣ − ٤ + ..... − ٩٨ + ٩٩",
    options: ["٥٠", "٥١", "٥٢", "٥٤"],
    correctAnswer: 0,
    explanation: "بتجميع الأزواج \\( (١−٢)+(٣−٤)+...+(٩٧−٩٨) = ٤٩\\times(−١) = −٤٩ \\)، ثم \\( +٩٩ = ٥٠ \\)",
    difficulty: "HARD",
  },
  {
    id: "timed-45",
    question: "ما قيمة ع إذا علمت أن \\( ٢ + \\left(\\frac{ع}{٢}\\right) = ١٤ \\) ؟",
    options: ["٢٠", "٢١", "٢٣", "٢٤"],
    correctAnswer: 3,
    explanation: "\\( \\frac{ع}{٢} = ١٢ \\Rightarrow ع = ٢٤ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-46",
    question: "ما العدد الذي يمكن كتابته على صورة \\( ٦ن \\) حيث ن عدد صحيح؟",
    options: ["٢٢٢", "٢٢٥", "٢٢٩", "٢٣٣"],
    correctAnswer: 0,
    explanation: "\\( ٢٢٢\\div٦=٣٧ \\) (عدد صحيح)، أما الباقي فليست من مضاعفات ٦.",
    difficulty: "EASY",
  },
  {
    id: "timed-47",
    question: "ما ناتج: \\( \\frac{٦٦٦}{٣٣٣} \\times \\left(\\frac{٤٤٤}{٥٥٥} \\div \\frac{٤٤٤}{٥٥٥}\\right) \\) ؟",
    options: ["١", "٢", "١١١", "٢٢٢"],
    correctAnswer: 1,
    explanation: "\\( \\frac{٦٦٦}{٣٣٣}=٢ \\)، وأي عدد مقسوماً على نفسه \\( =١ \\)، فالناتج \\( =٢\\times١=٢ \\)",
    difficulty: "EASY",
  },
  {
    id: "timed-48",
    question: "يقفز شخصان على خط أعداد مبتدئين من الصفر، الأول يقفز كل مرة ٥ والثاني يقفز كل مرة ٣. كم مرة يلتقيان قبل العدد ١٠٠؟",
    options: ["٢", "٣", "٥", "٦"],
    correctAnswer: 3,
    explanation: "يلتقيان عند مضاعفات م.م.أ(٥،٣)=١٥: أي عند ١٥،٣٠،٤٥،٦٠،٧٥،٩٠ = ٦ مرات قبل ١٠٠.",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-49",
    question: "أوجد الحد التالي في المتتابعة: ٢، ٥، ١٠، ١٧، ٢٦، .....",
    options: ["٣٧", "٣٨", "٤٠", "٧٤"],
    correctAnswer: 0,
    explanation: "الفروق ٣،٥،٧،٩ (تزيد بمقدار٢)، فالفرق التالي=١١، والحد التالي \\( =٢٦+١١=٣٧ \\)",
    difficulty: "MEDIUM",
  },
  {
    id: "timed-50",
    question: "زاويتان متقابلتان بالرأس، إحداهما \\( (٣س)° \\) والأخرى ٣٠°. أوجد قيمة س.",
    options: ["٣", "٥", "١٠", "٣٠"],
    correctAnswer: 2,
    explanation: "الزوايا المتقابلة بالرأس متساوية: \\( ٣س=٣٠ \\Rightarrow س=١٠ \\)",
    difficulty: "EASY",
  },
];

export default async function TimedPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");
  if (!session.user.isPremium) redirect("/packages");

  let questions = await prisma.question.findMany({
    where: { category: Category.EXAM_TIMED },
    take: 10,
    orderBy: { createdAt: "asc" },
  });

  const formattedQuestions = questions.length > 0
    ? questions.map((q) => ({
      id: q.id,
      question: q.question,
      options: q.options as string[],
      correctAnswer: q.correctAnswer,
      explanation: q.explanation ?? "",
    }))
    : FALLBACK_TIMED_QUESTIONS;

  return (
    <ExamClient
      title="أسئلة بتوقيت"
      userId={session.user.id}
      questions={formattedQuestions}
    />
  );
}

