import pg from "pg";

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

type Q = { question: string; options: string[]; correctAnswer: number; explanation: string; category: string; difficulty?: string };

const algebraQuestions: Q[] = [
  { question: "حل: \( ٤س - ٩ = ٣س + ٥ \)", options: ["\( ١٣ \)", "\( ١٤ \)", "\( ١١ \)", "\( ١٢ \)"], correctAnswer: 1, explanation: "ننقل الحدود: \( ٤س - ٣س = ٥ + ٩ \leftarrow س = ١٤ \).", category: "ALGEBRA" },
  { question: "حل: \( ٢(٣س - ٤) = ٤(س + ١ \))", options: ["\( ٥ \)", "\( ٤ \)", "\( ٧ \)", "\( ٦ \)"], correctAnswer: 3, explanation: "نفتح الأقواس: \( ٦س - ٨ = ٤س + ٤ \leftarrow ٢س = ١٢ \leftarrow س = ٦ \).", category: "ALGEBRA" },
  { question: "حل المعادلة: \( ٤(س + ٥) = ٣(س - ٣ \))", options: ["\( ٢١ \)", "\( ١٩ \)", "\( ٢٥ \)", "\( ٢٣ \)"], correctAnswer: 3, explanation: "\( بفك \) الأقواس وتبسيط الحدود المتشابهة: \( ٤س + ٢٠ = ٣س - ٣ \leftarrow س = -٢٣ \). القيمة المطلقة للناتج هي \( ٢٣ \).", category: "ALGEBRA" },
  { question: "إذا كان \( ٥س + ٣ = ٢س + ١٨ \)، فما قيمة \( ٣س - ٢ \)؟", options: ["\( ١٣ \)", "\( ١١ \)", "\( ١٠ \)", "\( ١٢ \)"], correctAnswer: 0, explanation: "أولاً \( نجد س: ٣س = ١٥ \leftarrow س = ٥ \). ثم نحسب المطلوب: \( ٣ \times ٥ - ٢ = ١٣ \).", category: "ALGEBRA" },
  { question: "حل: \( ٠.٥س - ١.٥ = ٠.٢٥س + ٠.٧٥ \)", options: ["\( ٩ \)", "\( ٨ \)", "\( ١١ \)", "\( ١٠ \)"], correctAnswer: 0, explanation: "بطرح الحدود المتشابهة: \( ٠.٢٥س = ٢.٢٥ \leftarrow س = ٩ \).", category: "ALGEBRA" },
  { question: "عدد يزيد ضعفه عن ثلثه بـ \( ٢٠ \). ما العدد؟", options: ["\( ٢٨ \)", "\( ٢٠ \)", "\( ٣٠ \)", "\( ١٢ \)"], correctAnswer: 3, explanation: "ليكن العدد \( س: ٢س - \frac{س}{٣} = ٢٠ \leftarrow \frac{٥س}{٣} = ٢٠ \leftarrow ٥س = ٦٠ \leftarrow س = ١٢ \).", category: "ALGEBRA" },
  { question: "ثلاثة أعداد متتالية مجموعها \( ٩٣ \). ما أكبرها؟", options: ["\( ٣٠ \)", "\( ٣١ \)", "\( ٣٢ \)", "\( ٣٣ \)"], correctAnswer: 2, explanation: "ليكن أصغرها \( س: س + (س+١) + (س+٢) = ٩٣ \leftarrow ٣س = ٩٠ \leftarrow س = ٣٠ \). العدد الأكبر هو \( س + ٢ = ٣٢ \).", category: "ALGEBRA" },
  { question: "عمر أحمد بعد \( ٨ \) سنوات يساوي ضعف عمره قبل \( ٤ \) سنوات. كم عمره الآن؟", options: ["\( ١٨ \)", "\( ٢٠ \)", "\( ١٤ \)", "\( ١٦ \)"], correctAnswer: 3, explanation: "\( أ + ٨ = ٢(أ - ٤) \leftarrow أ + ٨ = ٢أ - ٨ \leftarrow أ = ١٦ \).", category: "ALGEBRA" },
  { question: "مبلغ وُزّع على أخوين. الأول أخذ الثلث زائد \( ٢٠٠ \)، والثاني أخذ الثلثين ناقص \( ٢٠٠ \). ما المبلغ الكلي إذا كان نصيب الثاني \( ١٤٠٠ \)؟", options: ["\( ٢٨٠٠ \)", "\( ٢٤٠٠ \)", "\( ٣٢٠٠ \)", "\( ٣٠٠٠ \)"], correctAnswer: 1, explanation: "نصيب الثاني \( = ٢م/٣ - ٢٠٠ = ١٤٠٠ \leftarrow ٢م/٣ = ١٦٠٠ \leftarrow \) م \( = ٢٤٠٠ \).", category: "ALGEBRA" },
  { question: "سيارتان تسيران باتجاهين متعاكسين. الأولى بـ \( ٨٠ كم/س \) والثانية بـ \( ٦٠ كم/س \). بعد كم ساعة تكون المسافة بينهما \( ٤٢٠ \) كم؟", options: ["\( ٥ \)", "\( ٣ \)", "\( ٢ \)", "\( ٤ \)"], correctAnswer: 1, explanation: "المسافة الكلية \( = \) مجموع السرعتين \( \times \) الزمن: (\( ٨٠+٦٠) \times ز = ٤٢٠ \leftarrow ١٤٠ز = ٤٢٠ \leftarrow ز = ٣ \).", category: "ALGEBRA" },
  { question: "حل: \( س^{٢} - ٧س + ١٢ = ٠ \)", options: ["\( -١٢، -١ \)", "\( ١٢، ١ \)", "\( ٤، ٣ \)", "\( -٤، -٣ \)"], correctAnswer: 2, explanation: "نحلل العبارة التربيعية: (\( س-٣)(س-٤) = ٠ \leftarrow س = ٣ \) أو \( س = ٤ \).", category: "ALGEBRA" },
  { question: "حل: \( س^{٢} - ٢٥ = ٠ \)", options: ["\( ٦± \)", "\( ±٣ \)", "\( ±٥ \)", "\( ±٤ \)"], correctAnswer: 2, explanation: "بأخذ الجذر التربيعي للطرفين: \( س^{٢} = ٢٥ \leftarrow س = ±٥ \).", category: "ALGEBRA" },
  { question: "ما مجموع جذري: \( ٣س^{٢} - ٩س + ٦ = ٠ \)؟", options: ["\( ٣ \)", "\( ٤ \)", "\( ١ \)", "\( ٢ \)"], correctAnswer: 0, explanation: "قانون مجموع الجذرين \( = -ب/أ = -(-٩)/٣ = \frac{٩}{٣} = ٣ \).", category: "ALGEBRA" },
  { question: "ما حاصل ضرب جذري: \( ٢س^{٢} + ٥س - ١٢ = ٠ \)؟", options: ["\( ٦ \)", "\( ٥ \)", "\( -٦ \)", "\( -٥ \)"], correctAnswer: 2, explanation: "قانون حاصل ضرب الجذرين \( = ج/أ = -\frac{١٢}{٢} = -٦ \).", category: "ALGEBRA" },
  { question: "إذا كان أحد جذري \( س^{٢} - كس + ٨ = ٠ \) هو \( ٢ \)، فما قيمة \( ك \)؟", options: ["\( ٨ \)", "\( ٦ \)", "\( ٤ \)", "\( ٥ \)"], correctAnswer: 1, explanation: "حاصل ضرب الجذرين \( = ٨ \)، والجذر الأول \( = ٢ \)، إذن الجذر الثاني \( = ٨\div٢ = ٤ \). القيمة \( ك \) تمثل مجموع الجذرين \( = ٢ + ٤ = ٦ \).", category: "ALGEBRA" },
  { question: "حل بالتحليل: \( ٢س^{٢} - ٣س - ٢ = ٠ \)", options: ["\( -٢، \frac{١}{٢} \)", "\( ٢، -\frac{١}{٢} \)", "\( -٢، ١ \)", "\( ٢، -١ \)"], correctAnswer: 1, explanation: "نحلل العبارة: (\( ٢س+١)(س-٢) = ٠ \leftarrow س = -\frac{١}{٢} \) أو \( س = ٢ \).", category: "ALGEBRA" },
  { question: "مستطيل طوله يزيد عرضه بـ \( ٥ \). مساحته \( ٣٦ \). ما أبعاده؟", options: ["\( ١٢ \times ٣ \)", "\( ٣ \times ٩ \)", "\( ٤ \times ٩ \)", "\( ٦ \times ٦ \)"], correctAnswer: 2, explanation: "\( ع(ع+٥) = ٣٦ \leftarrow ع^{٢} + ٥ع - ٣٦ = ٠ \leftarrow (ع+٩)(ع-٤) = ٠ \leftarrow ع = ٤ \). إذن الأبعاد هي \( ٤ \times ٩ \).", category: "ALGEBRA" },
  { question: "عدد موجب تربيعه أكبر من ثلاثة أمثاله بـ \( ١٨ \). ما العدد؟", options: ["\( ٤ \)", "\( ٦ \)", "\( ٥ \)", "\( ٧ \)"], correctAnswer: 1, explanation: "\( س^{٢} = ٣س + ١٨ \leftarrow س^{٢} - ٣س - ١٨ = ٠ \leftarrow (س-٦)(س+٣) = ٠ \leftarrow س = ٦ \) لأنه حدد عدداً موجباً.", category: "ALGEBRA" },
  { question: "حل: \( س+ص=٧ \) و \( س-ص=٣ \). ما قيمة \( س\timesص \)؟", options: ["\( ٨ \)", "\( ١٠ \)", "\( ١٢ \)", "\( ١٦ \)"], correctAnswer: 1, explanation: "بالجمع: \( ٢س = ١٠ \leftarrow س = ٥ \). بالطرح: \( ٢ص = ٤ \leftarrow ص = ٢ \). إذن \( س\timesص = ١٠ \).", category: "ALGEBRA" },
  { question: "حل: \( ٢س+٣ص=١٢ \) و \( ٣س-ص=٧ \). ما قيمة \( س+ص \)؟", options: ["\( ٥ \)", "\( ٤ \)", "\( ٧ \)", "\( ٦ \)"], correctAnswer: 0, explanation: "من الثانية: \( ص = ٣س-٧ \). بتعويضها في الأولى: \( ٢س+٣(٣س-٧) = ١٢ \leftarrow ١١س = ٣٣ \leftarrow س = ٣، ص = ٢ \). إذن \( س+ص = ٥ \).", category: "ALGEBRA" },
  { question: "تفاحتان وثلاث برتقالات بـ \( ١٤ \) ريالاً. ثلاث تفاحات وبرتقالة بـ \( ١٣ \) ريالاً. ما سعر التفاحة؟", options: ["\( ٣.٥ \)", "\( ٣ \)", "\( ٤.٥ \)", "\( ٤ \)"], correctAnswer: 3, explanation: "\( ٢ت+٣ب=١٤ \) و \( ٣ت+ب=١٣ \). من الثانية: \( ب=١٣-٣ت \). بالتعويض: \( ٢ت+٣(١٣-٣ت)=١٤ \leftarrow -٧ت=-٢٨ \leftarrow ت=٤ \).", category: "ALGEBRA" },
  { question: "حل: \( س+ص+ز=١٠ \) و \( س+ص=٧ \) و \( ص+ز=٦ \). ما قيمة \( س \)؟", options: ["\( ٤ \)", "\( ٦ \)", "\( ٥ \)", "\( ٧ \)"], correctAnswer: 0, explanation: "من الأولى والثانية \( نجد ز = ١٠-٧ = ٣ \). من الثالثة: \( ص = ٦-٣ = ٣ \). من الثانية: \( س = ٧-٣ = ٤ \).", category: "ALGEBRA" },
  { question: "نقطة تقاطع المستقيمين: \( س+٢ص=٨ \) و \( ٢س-ص=٦ \)", options: ["(\( ٢، ٤ \))", "(\( ٥، ١.٥ \))", "(\( ٤، ٢ \))", "(\( ٣، ١.٥ \))"], correctAnswer: 2, explanation: "من الأولى: \( س = ٨-٢ص \). بالتعويض في الثانية: \( ٢(٨-٢ص)-ص = ٦ \leftarrow ١٦-٥ص = ٦ \leftarrow ص = ٢، س = ٤ \). النقطة هي (\( ٤، ٢ \)).", category: "ALGEBRA" },
  { question: "حلّل: \( س^{٢} - ٩ \)", options: ["(\( س-٣)(س+٣ \))", "\( س(س-٩ \))", "(\( س-٩)^{٢} \)", "(\( س+٣)^{٢} \)"], correctAnswer: 0, explanation: "تحليل فرق بين مربعين: \( أ^{٢}-ب^{٢} = (أ+ب)(أ-ب \))، إذن \( س^{٢}-٩ = (س+٣)(س-٣ \)).", category: "ALGEBRA" },
  { question: "حلّل: \( س^{٢} + ٥س + ٦ \)", options: ["(\( س+٢)(س+٣ \))", "\( س(س+٥ \))", "(\( س+٦)^{٢} \)", "(\( س-٢)(س-٣ \))"], correctAnswer: 0, explanation: "نبحث عن عددين مجموعهما \( ٥ \) وحاصل ضربهما \( ٦ \) وهما \( ٢ \) و \( ٣ \). إذن التحليل هو (\( س+٢)(س+٣ \)).", category: "ALGEBRA" },
  { question: "حلّل: \( ٢س^{٢} + ٨س \)", options: ["\( ٢س(س+٤ \))", "\( ٢(س^{٢}+٤س \))", "\( ٢س(س-٤ \))", "\( ٢(س^{٢}-٤س \))"], correctAnswer: 0, explanation: "باستخراج العامل المشترك الأكبر \( ٢س \) خارج القوس: \( ٢س^{٢} + ٨س = ٢س(س+٤ \)).", category: "ALGEBRA" },
  { question: "ما قيمة (\( س+ص)^{٣} \) إذا كان \( س+ص=٢ \) وس \( ص=-٣ \)؟", options: ["\( ٨- \)", "\( ٨ \)", "\( -٢ \)", "\( ٢ \)"], correctAnswer: 1, explanation: "المطلوب هو (\( س+ص)^{٣} \) والمقدار \( س+ص \) معطى مباشرة ويساوي \( ٢ \)، إذن \( ٢^{٣} = ٨ \).", category: "ALGEBRA" },
  { question: "ما قيمة \( س^{٣}+ص^{٣} \) إذا كان \( س+ص=٤ \) وسص=٣؟", options: ["\( ٢٤ \)", "\( ٣٠ \)", "\( ٣٢ \)", "\( ٢٨ \)"], correctAnswer: 3, explanation: "أولاً: \( س^{٢}+ص^{٢} = (س+ص)^{٢} - ٢سص = ١٦ - ٦ = ١٠ \). ثانياً: \( س^{٣}+ص^{٣} = (س+ص)(س^{٢} - سص + ص^{٢}) = ٤ \times (١٠ - ٣) = ٢٨ \).", category: "ALGEBRA" },
  { question: "بسّط: (\( س^{٢}-٤)/(س+٢ \))", options: ["\( س+٢ \)", "\( س-٢ \)", "\( ٢س \)", "\( ٣-س \)"], correctAnswer: 1, explanation: "بتحليل البسط كفرق مربعين: (\( س-٢)(س+٢) / (س+٢) = س-٢ \).", category: "ALGEBRA" },
  { question: "إذا كان \( س-\frac{١}{س}=٣ \)، فما قيمة \( س^{٢}+\frac{١}{س}^{٢} \)؟", options: ["\( ١١ \)", "\( ٩ \)", "\( ١٢ \)", "\( ١٠ \)"], correctAnswer: 0, explanation: "بتربيع الطرفين: (\( س-\frac{١}{س})^{٢} = ٩ \leftarrow س^{٢} - ٢ + \frac{١}{س}^{٢} = ٩ \leftarrow س^{٢} + \frac{١}{س}^{٢} = ١١ \).", category: "ALGEBRA" },
  { question: "إذا كانت \( ف(س)=٣س+١ \)، فما \( ف^{-١}(١٠ \))؟", options: ["\( ٢ \)", "\( ٣ \)", "\( ٥ \)", "\( ٤ \)"], correctAnswer: 1, explanation: "الدالة العكسية \( ف^{-١}(١٠ \)) تعني إيجاد قيمة \( س \) عندما \( ف(س)=١٠: ٣س+١ = ١٠ \leftarrow ٣س = ٩ \leftarrow س = ٣ \).", category: "ALGEBRA" },
  { question: "إذا كانت \( ف(س)=س^{٢}+٢ \) وج(س)=√س، فما \( ف(ج(٤ \)))؟", options: ["\( ٧ \)", "\( ٤ \)", "\( ٥ \)", "\( ٦ \)"], correctAnswer: 3, explanation: "أولاً نوجد الدالة الداخلية: \( ج(٤) = \sqrt{٤} = ٢ \). ثم الدالة الخارجية: \( ف(٢) = ٢^{٢} + ٢ = ٦ \).", category: "ALGEBRA" },
  { question: "الدالة \( ف(س)=٢س-٤ \). ما قيمة \( س \) عندما \( ف(س)=٠ \)؟", options: ["\( ٤ \)", "\( ٩ \)", "\( ٢ \)", "\( ١٠ \)"], correctAnswer: 2, explanation: "نساوي الدالة بالصفر: \( ٢س - ٤ = ٠ \leftarrow ٢س = ٤ \leftarrow س = ٢ \).", category: "ALGEBRA" },
  { question: "إذا كانت \( ف(س+٢)=٣س-١ \)، فما \( ف(٧ \))؟", options: ["\( ١٣ \)", "\( ١٢ \)", "\( ١٥ \)", "\( ١٤ \)"], correctAnswer: 3, explanation: "نضع \( س + ٢ = ٧ \leftarrow س = ٥ \). بتعويض قيمة \( س \) في الطرف الآخر: \( ف(٧) = ٣ \times ٥ - ١ = ١٤ \).", category: "ALGEBRA" },
  { question: "\( ف(س)=أس+ب، ف(٢)=٧ \) وف(−١)=١. ما قيمة \( أ+ب \)؟", options: ["\( ٧ \)", "\( ٥ \)", "\( ٤ \)", "\( ٦ \)"], correctAnswer: 1, explanation: "نعوض بالنقاط: \( ٢أ+ب=٧ \) و \( -أ+ب=١ \). بطرح المعادلتين: \( ٣أ=٦ \leftarrow أ=٢ \)، ومنها \( ب=٣ \). إذن \( أ+ب = ٥ \).", category: "ALGEBRA" },
  { question: "حل المتباينة: \( ٣س + ٥ > ١٤ \)", options: ["\( س < ٣ \)", "\( س > ٢ \)", "\( س > ٤ \)", "\( س > ٣ \)"], correctAnswer: 3, explanation: "بنقل الحدود الثابتة: \( ٣س > ١٤ - ٥ \leftarrow ٣س > ٩ \leftarrow س > ٣ \).", category: "ALGEBRA" },
  { question: "حل المتباينة: \( -٢س + ٦ ≥ ٢ \)", options: ["\( س ≤ ٢ \)", "\( س ≥ ٢ \)", "\( س ≤ ٤ \)", "\( س ≥ ٤ \)"], correctAnswer: 0, explanation: "\( -٢س ≥ ٢ - ٦ \leftarrow -٢س ≥ -٤ \leftarrow س ≤ ٢ \) (تنقلب إشارة المتباينة عند القسمة على عدد سالب).", category: "ALGEBRA" },
  { question: "حل: \( |٢س - ٣| ≤ ٧ \)", options: ["\( س ≤ ٥ \)", "\( س ≥ -٢ \)", "\( -٢ ≤ س ≤ ٥ \)", "\( س < -٢ \) أو \( س > ٥ \)"], correctAnswer: 2, explanation: "\( بفك \) المتباينة المطلقة: \( -٧ ≤ ٢س - ٣ ≤ ٧ \leftarrow -٤ ≤ ٢س ≤ ١٠ \leftarrow -٢ ≤ س ≤ ٥ \).", category: "ALGEBRA" },
  { question: "كم وحدة يجب إنتاجها على الأقل لتحقيق ربح إذا كان الربح \( = ٥س - ٢٠٠ \) وأردنا الربح \( > ٣٠٠ \)؟", options: ["\( ١١٠ \)", "\( ٩٩ \)", "\( ١٠٠ \)", "\( ١٠١ \)"], correctAnswer: 3, explanation: "\( ٥س - ٢٠٠ > ٣٠٠ \leftarrow ٥س > ٥٠٠ \leftarrow س > ١٠٠ \). إذن أقل عدد صحيح تالي يحقق الشرط هو \( ١٠١ \).", category: "ALGEBRA" },
  { question: "مزارع يريد تسوير حقل مستطيل محيطه على الأكثر \( ١٠٠م \) وطوله \( ٣٠م \). ما أقصى عرض؟", options: ["\( ٢٠ \)", "\( ١٥ \)", "\( ٣٠ \)", "\( ٢٥ \)"], correctAnswer: 0, explanation: "\( ٢(٣٠ + ع) ≤ ١٠٠ \leftarrow ٣٠ + ع ≤ ٥٠ \leftarrow ع ≤ ٢٠ \). أقصى عرض هو \( ٢٠م \).", category: "ALGEBRA" },
  { question: "رسوم نادٍ: اشتراك \( ٢٠٠ \) ريال \( + ٣٠ لكل \) زيارة. نادٍ آخر: \( ٥٠ لكل \) زيارة بلا اشتراك. ابتداءً من كم زيارة يصبح النادي الأول أوفر؟", options: ["\( ١١ \)", "\( ٩ \)", "\( ١٢ \)", "\( ١٠ \)"], correctAnswer: 0, explanation: "يكون النادي الأول أوفر عندما: \( ٢٠٠ + ٣٠ز < ٥٠ز \leftarrow ٢٠٠ < ٢٠ز \leftarrow ز > ١٠ \). إذن يصبح أوفر ابتداءً من الزيارة \( ١١ \).", category: "ALGEBRA" },
];

const geometryQuestions: Q[] = [
  { question: "مستطيل طوله \( ٨ \) سم وعرضه \( ٥ \) سم. ما مساحته؟", options: ["\( ٢٦ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 3, explanation: "المساحة \( = \) الطول \( \times \) العرض \( = ٨ \times ٥ = ٤٠ \) سم².", category: "GEOMETRY" },
  { question: "مربع طول ضلعه \( ٦ \) سم. ما محيطه؟", options: ["\( ٢٤ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 0, explanation: "المحيط \( = ٤ \times \) طول الضلع \( = ٤ \times ٦ = ٢٤ \) سم.", category: "GEOMETRY" },
  { question: "مثلث قاعدته \( ١٠ \) سم وارتفاعه \( ٦ \) سم. ما مساحته؟", options: ["\( ٢٦ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 1, explanation: "المساحة \( = \frac{١}{٢} \times \) القاعدة \( \times \) الارتفاع \( = \frac{١}{٢} \times ١٠ \times ٦ = ٣٠ \) سم².", category: "GEOMETRY" },
  { question: "دائرة نصف قطرها \( ٧ \) سم. ما تقريب محيطها؟ (\( \pi≈٣.١٤ \))", options: ["\( ٤٥.٧٨ \)", "\( ٤٤.٧٥ \)", "\( ٤٣.٩٦ \)", "\( ٤٠ \)"], correctAnswer: 2, explanation: "المحيط \( = ٢ \times \pi \times نق = ٢ \times ٣.١٤ \times ٧ = ٤٣.٩٦ \) سم.", category: "GEOMETRY" },
  { question: "دائرة نصف قطرها \( ٥ \) سم. ما مساحتها؟ (\( \pi≈٣.١٤ \))", options: ["\( ٢٦ \)", "\( ٣١.٤ \)", "\( ٥٠ \)", "\( ٧٨.٥ \)"], correctAnswer: 3, explanation: "المساحة \( = \pi \times نق^{٢} = ٣.١٤ \times ٢٥ = ٧٨.٥ \) سم².", category: "GEOMETRY" },
  { question: "متوازي أضلاع قاعدته \( ١٢ \) سم وارتفاعه \( ٧ \) سم. ما مساحته؟", options: ["\( ٩٦ \)", "\( ٣٠ \)", "\( ٨٤ \)", "\( ٧٦ \)"], correctAnswer: 2, explanation: "المساحة \( = \) القاعدة \( \times \) الارتفاع \( = ١٢ \times ٧ = ٨٤ \) سم².", category: "GEOMETRY" },
  { question: "شبه منحرف قاعدتاه \( ٨ \) و١٢ وارتفاعه \( ٥ \). ما مساحته؟", options: ["\( ٢٦ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٥٠ \)"], correctAnswer: 3, explanation: "المساحة \( = \frac{١}{٢} \times \) (القاعدة الأولى \( + \) القاعدة الثانية) \( \times \) الارتفاع \( = \frac{١}{٢} \times (٨+١٢) \times ٥ = ٥٠ \) سم².", category: "GEOMETRY" },
  { question: "مربع مساحته \( ٦٤ \) سم². ما طول ضلعه؟", options: ["\( ٨ \)", "\( ١٦ \)", "\( ٣٢ \)", "\( ٤ \)"], correctAnswer: 0, explanation: "طول الضلع \( = \sqrt{٦٤} = ٨ \) سم، لأن \( ٨ \times ٨ = ٦٤ \).", category: "GEOMETRY" },
  { question: "مستطيل محيطه \( ٣٦ \) سم وطوله \( ١٢ \) سم. ما عرضه؟", options: ["\( ٨ \)", "\( ٦ \)", "\( ١٠ \)", "\( ١٢ \)"], correctAnswer: 1, explanation: "نصف المحيط \( = ١٨ \) سم. بما أن الطول \( = ١٢ \) سم، إذن العرض \( = ١٨ - ١٢ = ٦ \) سم.", category: "GEOMETRY" },
  { question: "دائرة قطرها \( ١٠ \) سم. ما مساحتها؟ (\( \pi≈٣.١٤ \))", options: ["\( ١٥٧ \)", "\( ٣١٤ \)", "\( ٣١.٤ \)", "\( ٧٨.٥ \)"], correctAnswer: 3, explanation: "نصف القطر \( = ٥ \) سم، المساحة \( = ٣.١٤ \times ٥^{٢} = ٣.١٤ \times ٢٥ = ٧٨.٥ \) سم².", category: "GEOMETRY" },
  { question: "مجموع زوايا المثلث يساوي:", options: ["\( ١٨٠ \) درجة", "\( ٣٦٠ \) درجة", "\( ٩٠ \) درجة", "\( ٢٧٠ \) درجة"], correctAnswer: 0, explanation: "مجموع قياسات الزوايا الداخلية لأي مثلث يساوي دائماً \( ١٨٠ \) درجة.", category: "GEOMETRY" },
  { question: "في مثلث زاويتان \( ٦٠^\circ \) و٧٠°. ما قياس الزاوية الثالثة؟", options: ["\( ٧٠^\circ \)", "\( ٦٠^\circ \)", "\( ٥٠^\circ \)", "\( ٨٠^\circ \)"], correctAnswer: 2, explanation: "الزاوية الثالثة \( = ١٨٠^\circ - (٦٠^\circ + ٧٠^\circ) = ٥٠^\circ \).", category: "GEOMETRY" },
  { question: "الزاوية المجاورة لزاوية \( ٦٥^\circ \) على خط مستقيم تساوي:", options: ["\( ١١٠^\circ \)", "\( ١١٥^\circ \)", "\( ٨٥^\circ \)", "\( ١٠٥^\circ \)"], correctAnswer: 1, explanation: "الزاويتان المتجاورتان على خط مستقيم متكاملتان (مجموعهما \( ١٨٠^\circ): ١٨٠^\circ - ٦٥^\circ = ١١٥^\circ \).", category: "GEOMETRY" },
  { question: "مجموع زوايا المربع الداخلية يساوي:", options: ["\( ٥٤٠^\circ \)", "\( ٢٧٠^\circ \)", "\( ١٨٠^\circ \)", "\( ٣٦٠^\circ \)"], correctAnswer: 3, explanation: "المربع شكل رباعي، ومجموع الزوايا الداخلية لأي شكل رباعي يساوي \( ٣٦٠^\circ \).", category: "GEOMETRY" },
  { question: "المضلع السداسي المنتظم، ما قياس كل زاوية داخلية له؟", options: ["\( ١٢٠^\circ \)", "\( ١٠٨^\circ \)", "\( ١٥٠^\circ \)", "\( ١٣٥^\circ \)"], correctAnswer: 0, explanation: "قياس الزاوية الداخلية \( = (ن-٢) \times ١٨٠^\circ \div ن = (٦-٢) \times ١٨٠^\circ \div ٦ = ٧٢٠^\circ \div ٦ = ١٢٠^\circ \).", category: "GEOMETRY" },
  { question: "مثلث متساوي الساقين زاوية رأسه \( ٤٠^\circ \). ما قياس كل زاوية من زوايا القاعدة؟", options: ["\( ٢٦^\circ \)", "\( ٣٠^\circ \)", "\( ٤٥^\circ \)", "\( ٧٠^\circ \)"], correctAnswer: 3, explanation: "زوايا القاعدة متطابقة: (\( ١٨٠^\circ - ٤٠^\circ) \div ٢ = ١٤٠^\circ \div ٢ = ٧٠^\circ \).", category: "GEOMETRY" },
  { question: "مجموع زوايا مضلع عدد أضلاعه \( ٨ \) يساوي:", options: ["\( ١٢٦٠^\circ \)", "\( ٧٢٠^\circ \)", "\( ٩٠٠^\circ \)", "\( ١٠٨٠^\circ \)"], correctAnswer: 3, explanation: "مجموع الزوايا \( = (ن-٢) \times ١٨٠^\circ = (٨-٢) \times ١٨٠^\circ = ٦ \times ١٨٠^\circ = ١٠٨٠^\circ \).", category: "GEOMETRY" },
  { question: "في مثلث قائم الزاوية، طول الساقين \( ٣سم \) و٤سم. ما طول الوتر؟", options: ["\( ٥ \)", "\( ٦ \)", "\( ٧ \)", "\( ٨ \)"], correctAnswer: 0, explanation: "حسب نظرية فيثاغورس: الوتر \( = \sqrt{٣^{٢} + ٤^{٢}} = \sqrt{٩ + ١٦} = \sqrt{٢٥} = ٥ \) سم.", category: "GEOMETRY" },
  { question: "مكعب طول ضلعه \( ٤ \) سم. ما حجمه؟", options: ["\( ٣٢ \)", "\( ٤٨ \)", "\( ٦٤ \)", "\( ٢٤ \)"], correctAnswer: 2, explanation: "الحجم \( = \) طول الضلع³ \( = ٤ \times ٤ \times ٤ = ٦٤ \) سم³.", category: "GEOMETRY" },
  { question: "متوازي مستطيلات أبعاد أضلاعه \( ٣ \times ٤ \times ٥ \) سم. ما حجمه؟", options: ["\( ٢٦ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٦٠ \)"], correctAnswer: 3, explanation: "الحجم \( = \) الطول \( \times \) العرض \( \times \) الارتفاع \( = ٣ \times ٤ \times ٥ = ٦٠ \) سم³.", category: "GEOMETRY" },
  { question: "أريد تبليط غرفة أبعادها \( ٦م \times ٥م \) ببلاط مربع حجمه \( ٥٠سم \times ٥٠سم \). كم بلاطة أحتاج؟", options: ["\( ٩٠ \)", "\( ٢٤٠ \)", "\( ٦٠ \)", "\( ١٢٠ \)"], correctAnswer: 3, explanation: "مساحة الغرفة \( = ٣٠م^{٢} = ٣٠٠,٠٠٠ \) سم²، ومساحة البلاطة \( = ٢,٥٠٠ \) سم². عدد البلاط \( = ٣٠٠,٠٠٠ \div ٢,٥٠٠ = ١٢٠ \) بلاطة.", category: "GEOMETRY" },
  { question: "أسطوانة نصف قطرها \( ٣ \) سم وارتفاعها \( ١٠ \) سم. ما حجمها؟ (\( \pi≈٣.١٤ \))", options: ["\( ١٨٨.٤ \)", "\( ٣٧٦.٨ \)", "\( ٢٨٢.٦ \)", "\( ٩٤.٢ \)"], correctAnswer: 2, explanation: "الحجم \( = \pi \times نق^{٢} \times ع = ٣.١٤ \times ٩ \times ١٠ = ٢٨٢.٦ \) سم³.", category: "GEOMETRY" },
  { question: "معين طول قطريه \( ٨ \) سم و٦ سم. ما مساحته؟", options: ["\( ٢٦ \)", "\( ٢٤ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 1, explanation: "مساحة المعين \( = \) (القطر الأول \( \times \) القطر الثاني) \( \div ٢ = (٨ \times ٦) \div ٢ = ٢٤ \) سم².", category: "GEOMETRY" },
  { question: "دائرة مساحتها \( ١٥٤ \) سم². ما طول نصف قطرها؟ (\( \pi≈\frac{٢٢}{٧} \))", options: ["\( ٧ \)", "\( ١٤ \)", "\( ٢١ \)", "\( ٢٨ \)"], correctAnswer: 0, explanation: "\( ١٥٤ = (\frac{٢٢}{٧}) \times نق^{٢} \leftarrow نق^{٢} = ١٥٤ \times (\frac{٧}{٢٢}) = ٤٩ \leftarrow نق = ٧ \) سم.", category: "GEOMETRY" },
  { question: "المسافة بين نقطة الأصل (\( ٠,٠ \)) والنقطة (\( ٣,٤ \)) تساوي:", options: ["\( ٤ \)", "\( ٣ \)", "\( ٧ \)", "\( ٥ \)"], correctAnswer: 3, explanation: "المسافة \( = \sqrt{٣^{٢} + ٤^{٢}} = \sqrt{٩ + ١٦} = \sqrt{٢٥} = ٥ \).", category: "GEOMETRY" },
  { question: "إحداثيات نقطة \( منتصف \) القطعة المستقيمة الواصلة بين (\( ٢,٤ \)) و(٦,٨) هي:", options: ["(٤,٦)", "(٣,٥)", "(٥,٧)", "(٤,٥)"], correctAnswer: 0, explanation: "نقطة المنتصف \( = ((٢+٦)/٢ , (٤+٨)/٢) = (٤ , ٦ \)).", category: "GEOMETRY" },
  { question: "المسافة بين النقطتين (\( ١,٢ \)) و(٤,٦) تساوي:", options: ["\( ٦ \)", "\( ٥ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 1, explanation: "المسافة \( = \sqrt{(٤-١}^{٢} + (٦-٢)^{٢}) = \sqrt{٣^{٢} + ٤^{٢}} = \sqrt{٢٥} = ٥ \).", category: "GEOMETRY" },
  { question: "النقطة (\( -٣، ٢ \)) تقع في الربع الإحداثي:", options: ["الرابع", "الثالث", "الأول", "الثاني"], correctAnswer: 3, explanation: "الإحداثي السيني سالب والصادي موجب، وهذا يقع في الربع الثاني.", category: "GEOMETRY" },
  { question: "مثلثان متشابهان، أضلاع أحدهما \( ٣، ٤، ٥ \) سم ونسبة التشابه لهما \( ٢ \). ما طول أطول ضلع في المثلث الثاني؟", options: ["\( ٩ \)", "\( ٨ \)", "\( ١٠ \)", "\( ١٢ \)"], correctAnswer: 2, explanation: "أطول ضلع في المثلث الأصلي هو \( ٥ \) سم، نضربه في معامل التشابه: \( ٥ \times ٢ = ١٠ \) سم.", category: "GEOMETRY" },
  { question: "مثلثان متشابهان، نسبة الأضلاع المتناظرة لهما \( ٣:٥ \). ما هي نسبة مساحتيهما؟", options: ["\( ٩:٢٥ \)", "\( ٣:٥ \)", "\( ٢٦:٥ \)", "\( ٢٤:٥ \)"], correctAnswer: 0, explanation: "نسبة المساحات تساوي مربع نسبة الأضلاع المتناظرة: (\( \frac{٣}{٥})^{٢} = ٩:٢٥ \).", category: "GEOMETRY" },
  { question: "في مثلث قائم الزاوية طول الوتر \( ١٣ \) سم وإحدى الساقين \( ٥ \) سم. ما طول الساق الأخرى؟", options: ["\( ١٢ \)", "\( ١٠ \)", "\( ٨ \)", "\( ١١ \)"], correctAnswer: 0, explanation: "طول الساق الأخرى \( = \sqrt{١٣^{٢} - ٥^{٢}} = \sqrt{١٦٩ - ٢٥} = \sqrt{١٤٤} = ١٢ \) سم.", category: "GEOMETRY" },
  { question: "مستطيل مساحته \( ٦٠ \) سم² وطوله \( ١٢ \) سم. ما محيطه؟", options: ["\( ٢٦ \)", "\( ٣٤ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 1, explanation: "العرض \( = \) المساحة \( \div \) الطول \( = ٦٠ \div ١٢ = ٥ \) سم. المحيط \( = ٢ \times (١٢ + ٥) = ٣٤ \) سم.", category: "GEOMETRY" },
  { question: "مربع طول قطره \( ٨\sqrt{٢} \) سم. ما طول ضلعه؟", options: ["\( ٤ \)", "\( ٨ \)", "\( ٦ \)", "\( ١٠ \)"], correctAnswer: 1, explanation: "قطر المربع \( = \) طول الضلع \( \times \sqrt{٢} \). بالتالي طول الضلع \( = ٨\sqrt{٢} \div \sqrt{٢} = ٨ \) سم.", category: "GEOMETRY" },
  { question: "أريد طلاء جدار أبعاده \( ٥م \times ٣م \)، ويحتوي على باب بمساحة \( ١م \times ٢م \) ونافذة بمساحة \( ١م \times ١م \). ما صافي المساحة المطلوب طلاؤها؟", options: ["\( ١٢ \)", "\( ٢٢ \)", "\( ٥٠ \)", "\( ٤٤ \)"], correctAnswer: 0, explanation: "مساحة الجدار الكلية \( = ١٥م^{٢} \). مساحة الباب \( = ٢م^{٢} \)، مساحة النافذة \( = ١م^{٢} \). المساحة الصافية المتبقية للطلاء \( = ١٥ - (٢ + ١) = ١٢ \) م².", category: "GEOMETRY" },
];

const numbersQuestions: Q[] = [
  { question: "ما نسبة \( ١٥ \) إلى \( ٦٠ \) بأبسط صورة؟", options: ["\( ١:٤ \)", "\( ١:٣ \)", "\( ١:٢ \)", "\( ٢:٣ \)"], correctAnswer: 0, explanation: "نقسم كليهما على ق.م.أ=١٥: \( ١٥\div١٥=١، ٦٠\div١٥=٤ \)، إذن \( ١:٤ \).", category: "NUMBERS_EQUATIONS" },
  { question: "نسبة الطلاب الذكور إلى الإناث \( ٣:٢ \)، عدد الذكور \( ٦٠ \). كم عدد الإناث؟", options: ["\( ٤٥ \)", "\( ٤٠ \)", "\( ٥٠ \)", "\( ٣٠ \)"], correctAnswer: 1, explanation: "الإناث \( = ٦٠ \times (\frac{٢}{٣}) = ٤٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "إذا كان \( \frac{س}{٤} = \frac{١٢}{١٦} \)، فما قيمة \( س \)؟", options: ["\( ٣ \)", "\( ٦ \)", "\( ٨ \)", "\( ٤ \)"], correctAnswer: 0, explanation: "تضريب متقاطع: \( ١٦س = ٤٨ \leftarrow س = ٣ \).", category: "NUMBERS_EQUATIONS" },
  { question: "سيارة تقطع \( ٢٤٠ \) كم في \( ٣ \) ساعات. كم تقطع في \( ٥ \) ساعات؟", options: ["\( ٣٠٠ \)", "\( ٤٥٠ \)", "\( ٥٠٠ \)", "\( ٤٠٠ \)"], correctAnswer: 3, explanation: "السرعة \( = ٢٤٠ \div ٣ = ٨٠ كم/س \)، إذن \( ٨٠ \times ٥ = ٤٠٠ \) كم.", category: "NUMBERS_EQUATIONS" },
  { question: "\( أ:ب = ٢:٣ \) و \( ب:ج = ٣:٤ \). ما \( أ:ج \)؟", options: ["\( ١:٤ \)", "\( ٢:٣ \)", "\( ١:٢ \)", "\( ٣:٤ \)"], correctAnswer: 2, explanation: "\( أ:ب:ج = ٢:٣:٤ \leftarrow أ:ج = ٢:٤ = ١:٢ \).", category: "NUMBERS_EQUATIONS" },
  { question: "قسّم \( ١٢٠ \) ريالاً بنسبة \( ٣:٥ \). ما نصيب الأول؟", options: ["\( ٤٥ \)", "\( ٤٠ \)", "\( ٥٠ \)", "\( ٣٠ \)"], correctAnswer: 0, explanation: "نصيب الأول \( = ١٢٠ \times (\frac{٣}{٨}) = ٤٥ \) ريالاً.", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة \( ٤٠\text{٪} \) من \( ٢٥٠ \)؟", options: ["\( ١٠٠ \)", "\( ٩٠ \)", "\( ٨٠ \)", "\( ١٢٠ \)"], correctAnswer: 0, explanation: "\( ٢٥٠ \times ٠.٤ = ١٠٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ارتفع سعر السلعة من \( ٨٠ \) إلى \( ١٠٠ \). ما نسبة الزيادة؟", options: ["\( ٢٠\text{٪} \)", "\( ١٥\text{٪} \)", "\( ٢٥\text{٪} \)", "\( ٣٠\text{٪} \)"], correctAnswer: 2, explanation: "الزيادة \( = ٢٠ \)، نسبة الزيادة \( = ٢٠ \div ٨٠ \times ١٠٠ = ٢٥\text{٪} \).", category: "NUMBERS_EQUATIONS" },
  { question: "خصم \( ١٥\text{٪} \) من سعر \( ٤٠٠ \) ريال. ما السعر الجديد؟", options: ["\( ٣٤٠ \)", "\( ٣٦٠ \)", "\( ٣٨٠ \)", "\( ٣٢٠ \)"], correctAnswer: 0, explanation: "\( ٤٠٠ \times ٠.٨٥ = ٣٤٠ \) ريالاً.", category: "NUMBERS_EQUATIONS" },
  { question: "\( ٣٠\text{٪} \) من عدد \( = ٩٠ \). ما \( ٥٠\text{٪} \) من \( نفس \) العدد؟", options: ["\( ١٣٠ \)", "\( ١٢٠ \)", "\( ١٨٠ \)", "\( ١٥٠ \)"], correctAnswer: 3, explanation: "العدد \( = ٩٠ \div ٠.٣ = ٣٠٠ \)، إذن \( ٥٠\text{٪} \) منه \( = ٣٠٠ \times ٠.٥ = ١٥٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "\( أ \) يُنجز عملاً في \( ٦ \) أيام، \( ب \) في \( ١٢ \) يوماً. كم يحتاجان معاً؟", options: ["\( ٤ \)", "\( ٦ \)", "\( ٥ \)", "\( ٣ \)"], correctAnswer: 0, explanation: "في اليوم: \( \frac{١}{٦} + \frac{١}{١٢} = \frac{٣}{١٢} = \frac{١}{٤} \)، إذن يحتاجان \( ٤ \) أيام.", category: "NUMBERS_EQUATIONS" },
  { question: "أُضيف \( ٢٠\text{٪} \) ثم خُفّض \( ٢٠\text{٪} \). ما نسبة التغيير الإجمالية؟", options: ["\( ٠\text{٪} \)", "\( -٢\text{٪} \)", "\( -٤\text{٪} \)", "\( ٤\text{٪} \)"], correctAnswer: 2, explanation: "\( ١.٢ \times ٠.٨ = ٠.٩٦ \leftarrow \) خسارة \( ٤\text{٪} \).", category: "NUMBERS_EQUATIONS" },
  { question: "ربح \( ٢٥\text{٪} \) على تكلفة \( ٢٠٠ \) ريال. ما سعر البيع؟", options: ["\( ٢٢٥ \)", "\( ٢٤٠ \)", "\( ٢٢٠ \)", "\( ٢٥٠ \)"], correctAnswer: 3, explanation: "\( ٢٠٠ \times ١.٢٥ = ٢٥٠ \) ريالاً.", category: "NUMBERS_EQUATIONS" },
  { question: "\( ٨ \) عمال ينهون عملاً في \( ٦ \) أيام. كم يوماً لـ \( ١٢ \) عاملاً؟", options: ["\( ٣ \)", "\( ٤ \)", "\( ٦ \)", "\( ٥ \)"], correctAnswer: 1, explanation: "تناسب عكسي: \( ٨ \times ٦ = ١٢ \times \) أيام \( \leftarrow \) أيام \( = ٤ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( ٣ + ٤ \times ٢ \) ؟", options: ["\( ١١ \)", "\( ١٤ \)", "\( ١٠ \)", "\( ٩ \)"], correctAnswer: 0, explanation: "الضرب أولاً: \( ٤ \times ٢ = ٨ \)، ثم \( ٣ + ٨ = ١١ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: (\( ٦ + ٢) \times ٣ - ٤ \) ؟", options: ["\( ٢٢ \)", "\( ٢٠ \)", "\( ١٢ \)", "\( ١٦ \)"], correctAnswer: 1, explanation: "القوس أولاً: (\( ٦+٢) = ٨ \)، ثم \( ٨ \times ٣ = ٢٤ \)، ثم \( ٢٤ - ٤ = ٢٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( ٢٠ \div ٤ + ٣ \times ٢ - ١ \) ؟", options: ["\( ١٢ \)", "\( ٩ \)", "\( ١٥ \)", "\( ١٠ \)"], correctAnswer: 3, explanation: "\( ٢٠ \div ٤ = ٥ \)، و \( ٣ \times ٢ = ٦ \)، إذن \( ٥ + ٦ - ١ = ١٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( \frac{١}{٢} + \frac{١}{٤} \) ؟", options: ["\( \frac{١}{٤} \)", "\( \frac{٢}{٤} \)", "\( \frac{٣}{٤} \)", "\( \frac{٤}{٤} \)"], correctAnswer: 2, explanation: "مقام مشترك \( = ٤: \frac{٢}{٤} + \frac{١}{٤} = \frac{٣}{٤} \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( \frac{٢}{٣} \times \frac{٣}{٤} \) ؟", options: ["\( \frac{٧}{١٢} \)", "\( \frac{٣}{٥} \)", "\( \frac{٢}{٣} \)", "\( \frac{١}{٢} \)"], correctAnswer: 3, explanation: "\( \frac{٢}{٣} \times \frac{٣}{٤} = \frac{٦}{١٢} = \frac{١}{٢} \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( \frac{٣}{٤} \div \frac{٣}{٨} \) ؟", options: ["\( ١\frac{١}{٢} \)", "\( \frac{٩}{٣٢} \)", "\( ٢ \)", "\( ٣ \)"], correctAnswer: 2, explanation: "اقلب المقسوم عليه واضرب: \( \frac{٣}{٤} \times \frac{٨}{٣} = \frac{٢٤}{١٢} = ٢ \).", category: "NUMBERS_EQUATIONS" },
  { question: "\( \frac{٣}{٥} \) من عدد \( = ٢٤ \). ما العدد؟", options: ["\( ٣٢ \)", "\( ٣٦ \)", "\( ٤٠ \)", "\( ٤٨ \)"], correctAnswer: 2, explanation: "العدد \( = ٢٤ \div (\frac{٣}{٥}) = ٢٤ \times \frac{٥}{٣} = ٤٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( ٠.٧ + ٠.٣٨ \) ؟", options: ["\( ١.٠٨ \)", "\( ١.١٨ \)", "\( ١.٢٨ \)", "\( ١.٣٨ \)"], correctAnswer: 0, explanation: "\( ٠.٧٠ + ٠.٣٨ = ١.٠٨ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( ٣.٦ \times ٠.٥ \) ؟", options: ["\( ٣.١ \)", "\( ١.٨ \)", "\( ٢.٢ \)", "\( ٢.٤ \)"], correctAnswer: 1, explanation: "الضرب في \( ٠.٥ = \) نصف العدد: \( ٣.٦ \div ٢ = ١.٨ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما ناتج: \( ٢.٤ \div ٠.٠٦ \) ؟", options: ["\( ٠.٤ \)", "\( ٤٠٠ \)", "\( ٤٠ \)", "\( ٠.٠٠٤ \)"], correctAnswer: 2, explanation: "اضرب كليهما في \( ١٠٠: ٢٤٠ \div ٦ = ٤٠ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( ٢^{٥} \) ؟", options: ["\( ٣٢ \)", "\( ٦٤ \)", "\( ١٢٨ \)", "\( ٢٥٦ \)"], correctAnswer: 0, explanation: "\( ٢^{٥} = ٢ \times ٢ \times ٢ \times ٢ \times ٢ = ٣٢ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( ٣^{٤} \div ٣^{٢} \) ؟", options: ["\( ٩ \)", "\( ٢٧ \)", "\( ٨١ \)", "\( ٢٤٣ \)"], correctAnswer: 0, explanation: "\( ٣^{٤} \div ٣^{٢} = ٣^(٤-٢) = ٣^{٢} = ٩ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: (\( ٢^{٣})^{٢} \) ؟", options: ["\( ١٦ \)", "\( ٣٢ \)", "\( ١٢٨ \)", "\( ٦٤ \)"], correctAnswer: 3, explanation: "قوة على قوة: \( ٢^(٣\times٢) = ٢⁶ = ٦٤ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( ٥^{٠} + ٤^{١} + ٢^{-١} \) ؟", options: ["\( ٥.٥ \)", "\( ٦ \)", "\( ٧ \)", "\( ٤.٥ \)"], correctAnswer: 0, explanation: "\( ٥^{٠} = ١، ٤^{١} = ٤، ٢^{-١} = ٠.٥ \). المجموع \( = ١ + ٤ + ٠.٥ = ٥.٥ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( \sqrt{١٤٤} \) ؟", options: ["\( ١٢ \)", "\( ١٣ \)", "\( ١٤ \)", "\( ١١ \)"], correctAnswer: 0, explanation: "\( ١٢ \times ١٢ = ١٤٤ \)، إذن \( \sqrt{١٤٤} = ١٢ \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( \sqrt{٧٢} \) بأبسط صورة؟", options: ["\( ٢\sqrt{٦} \)", "\( ٣\sqrt{٨} \)", "\( ٣\sqrt{٢} \)", "\( ٦\sqrt{٢} \)"], correctAnswer: 3, explanation: "\( ٧٢ = ٣٦ \times ٢ \)، إذن \( \sqrt{٧٢} = \sqrt{٣٦} \times \sqrt{٢} = ٦\sqrt{٢} \).", category: "NUMBERS_EQUATIONS" },
  { question: "ما قيمة: \( \sqrt{٣} \times \sqrt{١٢} \) ؟", options: ["\( ٤\sqrt{٣} \)", "\( ٢\sqrt{٣} \)", "\( ٦ \)", "\( \sqrt{٥} \)"], correctAnswer: 2, explanation: "\( \sqrt{٣} \times \sqrt{١٢} = \sqrt{٣٦} = ٦ \).", category: "NUMBERS_EQUATIONS" },
];

const probabilityQuestions: Q[] = [
  { question: "كيس فيه \( ٤ \) كرات حمراء و٦ زرقاء. ما احتمال سحب كرة حمراء؟", options: ["\( \frac{٢}{٥} \)", "\( \frac{٣}{٥} \)", "\( \frac{٢}{٣} \)", "\( \frac{١}{٢} \)"], correctAnswer: 0, explanation: "عدد الكرات الحمراء \( = ٤ \)، الإجمالي \( = ١٠ \). الاحتمال \( = \frac{٤}{١٠} = \frac{٢}{٥} \).", category: "PROBABILITY" },
  { question: "رُمي حجر نرد. ما احتمال ظهور عدد أقل من \( ٤ \)؟", options: ["\( \frac{١}{٣} \)", "\( \frac{١}{٢} \)", "\( \frac{٢}{٣} \)", "\( \frac{٥}{٦} \)"], correctAnswer: 1, explanation: "الأعداد الأقل من \( ٤ \) هي: \( ١، ٢، ٣ \) (وهي \( ٣ \) أعداد من \( أصل ٦ \)). الاحتمال \( = \frac{٣}{٦} = \frac{١}{٢} \).", category: "PROBABILITY" },
  { question: "رُميت قطعة نقود مرتين. ما احتمال ظهور صورتين؟", options: ["\( \frac{١}{٢} \)", "\( \frac{١}{٣} \)", "\( \frac{١}{٤} \)", "\( \frac{١}{٨} \)"], correctAnswer: 2, explanation: "احتمال الصورة في كل رمية \( = \frac{١}{٢} \). الاحتمال المشترك للحدثين المستقلين \( = \frac{١}{٢} \times \frac{١}{٢} = \frac{١}{٤} \).", category: "PROBABILITY" },
  { question: "كم طريقة لترتيب \( ٥ \) كتب مختلفة على رف؟", options: ["\( ٢٠ \)", "\( ٦٠ \)", "\( ١٢٠ \)", "\( ٢٤٠ \)"], correctAnswer: 2, explanation: "عدد التراتيب هو مضروب العدد: \( ٥! = ٥ \times ٤ \times ٣ \times ٢ \times ١ = ١٢٠ \).", category: "PROBABILITY" },
  { question: "كم طريقة لاختيار \( ٢ \) طلاب من \( ٦ \) لتمثيل الفصل؟", options: ["\( ١٢ \)", "\( ١٥ \)", "\( ٢٠ \)", "\( ٣٠ \)"], correctAnswer: 1, explanation: "باستخدام التوافيق: \( ٦! \div (٢! \times ٤!) = (٦ \times ٥) \div ٢ = ١٥ \).", category: "PROBABILITY" },
  { question: "حدثان مستقلان احتمال \( أ=٠.٥ \) واحتمال \( ب=٠.٦ \). ما احتمال وقوع كليهما؟", options: ["\( ٠.٣ \)", "\( ٠.٤ \)", "\( ٠.٥ \)", "\( ١.١ \)"], correctAnswer: 0, explanation: "في الأحداث المستقلة نضرب الاحتمالين معاً: \( ٠.٥ \times ٠.٦ = ٠.٣ \).", category: "PROBABILITY" },
  { question: "صندوق فيه \( ١٠ \) كرات: \( ٣ \) خضراء و٧ غير خضراء. ما احتمال \( عدم \) سحب كرة خضراء؟", options: ["\( \frac{٣}{١٠} \)", "\( \frac{٧}{١٠} \)", "\( \frac{١}{٣} \)", "\( \frac{١}{٢} \)"], correctAnswer: 1, explanation: "عدد الكرات غير الخضراء \( = ٧ \) من \( أصل ١٠ \). الاحتمال \( = \frac{٧}{١٠} \).", category: "PROBABILITY" },
  { question: "في \( فصل ٢٥ \) طالباً، \( ١٥ \) يحبون كرة القدم. اختُير طالب عشوائياً. ما احتمال أنه يحب كرة القدم؟", options: ["\( \frac{٢}{٥} \)", "\( \frac{٣}{٥} \)", "\( \frac{١}{٢} \)", "\( \frac{٧}{١٠} \)"], correctAnswer: 1, explanation: "الاحتمال \( = \frac{١٥}{٢٥} = \frac{٣}{٥} \).", category: "PROBABILITY" },
  { question: "عند رمي قطعة نقدية \( ٤ \) مرات، ما احتمال أن تظهر الكتابة في الأربع مرات معاً؟", options: ["\( \frac{١}{١٦} \)", "\( \frac{١}{١٢} \)", "\( \frac{١}{٨} \)", "\( \frac{٣}{٤} \)"], correctAnswer: 0, explanation: "احتمال ظهور الكتابة في الرمية الواحدة هو \( \frac{١}{٢} \). بما أن الرميات مستقلة: (\( \frac{١}{٢})^{٤} = \frac{١}{١٦} \).", category: "PROBABILITY" },
];

const patternsQuestions: Q[] = [
  { question: "متتالية حسابية أول حدودها \( ٤ \) وفرقها \( ٥ \). ما الحد الثامن؟", options: ["\( ٣٤ \)", "\( ٣٧ \)", "\( ٣٩ \)", "\( ٤٤ \)"], correctAnswer: 2, explanation: "الحد الثامن \( = أ + (ن-١)\timesد = ٤ + (٧ \times ٥) = ٤ + ٣٥ = ٣٩ \).", category: "PATTERNS" },
  { question: "متتالية هندسية أول حدودها \( ٣ \) ونسبتها \( ٢ \). ما الحد السادس؟", options: ["\( ٤٨ \)", "\( ٦٤ \)", "\( ٩٦ \)", "\( ١٢٨ \)"], correctAnswer: 2, explanation: "الحد السادس \( = أ \times \) ر⁵ \( = ٣ \times ٢^{٥} = ٣ \times ٣٢ = ٩٦ \).", category: "PATTERNS" },
  { question: "ما الحد التالي في النمط: \( ٣، ٧، ١٢، ١٨، ٢٥ \)، ؟", options: ["\( ٣٢ \)", "\( ٣٣ \)", "\( ٣٤ \)", "\( ٣٥ \)"], correctAnswer: 1, explanation: "الفروق المتتالية هي: \( +٤، +٥، +٦، +٧ \)، والمقبل \( +٨ \). إذن \( ٢٥ + ٨ = ٣٣ \).", category: "PATTERNS" },
  { question: "ما مجموع أول \( ١٥ \) عدداً طبيعياً؟", options: ["\( ١٠٥ \)", "\( ١١٠ \)", "\( ١١٥ \)", "\( ١٢٠ \)"], correctAnswer: 3, explanation: "قانون المجموع للمتتالية \( = ن(ن+١) \div ٢ = ١٥ \times ١٦ \div ٢ = ١٢٠ \).", category: "PATTERNS" },
  { question: "متتالية: \( ١، ٤، ٩، ١٦، ٢٥ \)، ؟ ما الحد التالي؟", options: ["\( ٣٠ \)", "\( ٣٢ \)", "\( ٣٤ \)", "\( ٣٦ \)"], correctAnswer: 3, explanation: "الحدود تمثل مربعات الأعداد: \( ١^{٢}، ٢^{٢}، ٣^{٢}، ٤^{٢}، ٥^{٢} \). الحد التالي \( = ٦^{٢} = ٣٦ \).", category: "PATTERNS" },
];

const ratioQuestions: Q[] = [
  { question: "نسبة \( ٤٨ \) إلى \( ٦٤ \) بأبسط صورة:", options: ["\( ٣:٤ \)", "\( ٤:٥ \)", "\( ٢:٣ \)", "\( ٥:٦ \)"], correctAnswer: 0, explanation: "نقسم كليهما على ق.م.أ=١٦: \( ٤٨\div١٦=٣، ٦٤\div١٦=٤ \)، إذن النسبة \( ٣:٤ \).", category: "RATIO" },
  { question: "قُسّمت \( ٤٥٠ \) ريالاً بنسبة \( ٢:٧ \). ما نصيب الأقل؟", options: ["\( ٨٠ \)", "\( ٩٠ \)", "\( ١٠٠ \)", "\( ١١٠ \)"], correctAnswer: 2, explanation: "المجموع \( ٩ \) وحدات. نصيب الأقل \( = ٤٥٠ \times \frac{٢}{٩} = ١٠٠ \) ريال.", category: "RATIO" },
  { question: "سيارة تقطع \( ٢١٠ \) كم بـ \( ١٤ \) لتراً. كم تقطع بـ \( ٢٠ \) لتراً؟", options: ["\( ٢٧٠ \)", "\( ٢٨٠ \)", "\( ٣٠٠ \)", "\( ٣٢٠ \)"], correctAnswer: 2, explanation: "\( معدل \) الاستهلاك \( = ٢١٠\div١٤ = ١٥ \) كم/لتر. إذن \( ١٥\times٢٠ = ٣٠٠ \) كم.", category: "RATIO" },
  { question: "\( ٦ \) عمال ينجزون عملاً في \( ١٢ \) يوماً. كم يوماً يحتاج \( ٨ \) عمال؟", options: ["\( ٧ \)", "\( ٨ \)", "\( ٩ \)", "\( ١٠ \)"], correctAnswer: 2, explanation: "تناسب عكسي: \( ٦\times١٢ = \) ٨×أيام \( \leftarrow \) أيام \( = ٧٢\div٨ = ٩ \).", category: "RATIO" },
  { question: "\( أ:ب = ٣:٥ \) و \( ب:ج = ٥:٨ \). ما \( أ:ج \)؟", options: ["\( ٣:٨ \)", "\( ٣:١٣ \)", "\( ٨:٣ \)", "\( ٥:٨ \)"], correctAnswer: 0, explanation: "نوحّد \( ب: أ:ب=٣:٥، ب:ج=٥:٨ \). القيمة المشتركة لـ \( ب \) هي \( ٥ \)، إذن \( أ:ج = ٣:٨ \) مباشرة.", category: "RATIO" },
  { question: "نسبة طلاب \( أ \) إلى \( ب \) هي \( ٣:٤ \). إذا كان مجموعهم \( ١٤٠ \)، فما عدد طلاب \( ب \)؟", options: ["\( ٦٠ \)", "\( ٧٠ \)", "\( ٨٠ \)", "\( ٩٠ \)"], correctAnswer: 2, explanation: "المجموع \( ٧ \) وحدات، قيمة الوحدة \( = ٢٠. ب = ٤ \times ٢٠ = ٨٠ \) طالباً.", category: "RATIO" },
  { question: "إذا كان \( \frac{٥}{٨} \) من عدد \( = ٤٠ \)، فما العدد؟", options: ["\( ٥٠ \)", "\( ٥٦ \)", "\( ٦٤ \)", "\( ٧٢ \)"], correctAnswer: 2, explanation: "العدد \( = ٤٠ \div \frac{٥}{٨} = ٤٠ \times \frac{٨}{٥} = ٦٤ \).", category: "RATIO" },
  { question: "ما قيمة \( ٤٥\text{٪} \) من \( ٣٢٠ \)؟", options: ["\( ١٢٤ \)", "\( ١٣٢ \)", "\( ١٤٤ \)", "\( ١٥٠ \)"], correctAnswer: 2, explanation: "\( ٣٢٠ \times ٠.٤٥ = ١٤٤ \).", category: "RATIO" },
  { question: "بعد خصم \( ٢٠\text{٪} \) أصبح سعر \( منتج ٤٨٠ \) ريالاً. ما سعره الأصلي؟", options: ["\( ٥٤٠ \)", "\( ٥٧٦ \)", "\( ٦٠٠ \)", "\( ٦٢٤ \)"], correctAnswer: 2, explanation: "السعر الأصلي \( = ٤٨٠ \div ٠.٨ = ٦٠٠ \) ريال.", category: "RATIO" },
  { question: "حصل طالب على \( ٦٨ \) من \( ٨٠ \). ما نسبته المئوية؟", options: ["\( ٧٥\text{٪} \)", "\( ٨٠\text{٪} \)", "\( ٨٥\text{٪} \)", "\( ٩٠\text{٪} \)"], correctAnswer: 2, explanation: "\( ٦٨ \div ٨٠ \times ١٠٠ = ٨٥\text{٪} \).", category: "RATIO" },
  { question: "اشترى تاجر بضاعة بـ \( ٩٠٠ \) ريال وباعها بـ \( ١١٢٥ \) ريالاً. ما نسبة الربح؟", options: ["\( ٢٠\text{٪} \)", "\( ٢٢\text{٪} \)", "\( ٢٥\text{٪} \)", "\( ٣٠\text{٪} \)"], correctAnswer: 2, explanation: "الربح \( = ٢٢٥ \). النسبة \( = ٢٢٥ \div ٩٠٠ \times ١٠٠ = ٢٥\text{٪} \).", category: "RATIO" },
  { question: "ما العدد الذي \( ٣٠\text{٪} \) منه يساوي \( ٦٠ \)؟", options: ["\( ١٨٠ \)", "\( ٢٠٠ \)", "\( ٢١٠ \)", "\( ٢٢٠ \)"], correctAnswer: 1, explanation: "\( ٠.٣ \times س = ٦٠ \leftarrow س = ٦٠ \div ٠.٣ = ٢٠٠ \).", category: "RATIO" },
  { question: "راتب موظف \( ٥٠٠٠ \). زاد \( ١٠\text{٪} \) ثم \( نزل ١٠\text{٪} \). ما الراتب النهائي؟", options: ["\( ٤٩٥٠ \)", "\( ٥٠٠٠ \)", "\( ٥٠٥٠ \)", "\( ٥١٠٠ \)"], correctAnswer: 0, explanation: "\( ٥٠٠٠ \times ١.١ \times ٠.٩ = ٥٥٠٠ \times ٠.٩ = ٤٩٥٠ \).", category: "RATIO" },
  { question: "بضاعة بيعت بـ \( ٦٩٠ \) ريالاً بعد إضافة ضريبة \( ١٥\text{٪} \). ما ثمنها قبل الضريبة؟", options: ["\( ٥٧٥ \)", "\( ٥٨٥ \)", "\( ٦٠٠ \)", "\( ٦١٥ \)"], correctAnswer: 2, explanation: "الثمن \( \times ١.١٥ = ٦٩٠ \leftarrow \) الثمن \( = ٦٩٠ \div ١.١٥ = ٦٠٠ \) ريال.", category: "RATIO" },
  { question: "\( أ:ب:ج = ١:٢:٣ \) ومجموعهم \( ١٢٠ \). ما قيمة \( ب \)؟", options: ["\( ٣٠ \)", "\( ٢٠ \)", "\( ٥٠ \)", "\( ٤٠ \)"], correctAnswer: 3, explanation: "\( ١٢٠ \times (\frac{٢}{٦}) = ٤٠ \).", category: "RATIO" },
];

const exam2025Questions: Q[] = [
  { question: "نقاط في المستوى الأحداثي (م ، \( ن \) ، \( ج \) ، \( ل \) ، \( ف \)) تمثل قرى، إذا كانت (\( ل \)) تقع شرق (\( م \)) وغرب (\( ن \))، و (\( ج \)) تقع جنوب شرق (\( ن \))، و (\( م \)) تقع جنوب شرق (\( ف \))، فأي حرف يقع في أقصى الغرب؟", options: ["\( ف \)", "\( ج \)", "\( ن \)", "\( ل \)"], correctAnswer: 0, explanation: "بترتيب مواقع القرى من الشرق إلى الغرب حسب اتجاهات المعطيات، \( نجد \) أن القرية (\( ف \)) تقع في أقصى جهة الغرب.", category: "EXAM_2025" },
  { question: "قارن بين: القيمة الأولى: \( ٤١ | \) القيمة الثانية: \( ٤ + (٣ + ٤)^{٢} - (٤ - ٢)^{-٣} \)", options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctAnswer: 1, explanation: "القيمة الثانية \( = ٤ + ٤٩ - \frac{١}{٨} = ٥٢.٨٧٥ \). وهي أكبر من القيمة الأولى (\( ٤١ \)).", category: "EXAM_2025" },
  { question: "إذا كان \( ١ \) دولار \( = ٣ \) ليرات، \( ١٠ \) دولار \( = ٨ \) جنيهات، فإن \( ١٥ \) ليرة تساوي ...... جنيه؟", options: ["\( ٤ \)", "\( ٣ \)", "\( ٦ \)", "\( ٨ \)"], correctAnswer: 0, explanation: "\( ٥ \) دولار \( = ١٥ \) ليرة، و٥ دولار \( = ٤ \) جنيهات. إذن \( ١٥ \) ليرة \( = ٤ \) جنيهات.", category: "EXAM_2025" },
  { question: "ما رقم آحاد ناتج ضرب أول \( ١٠٠ \) عدد أولي؟", options: ["\( ٠ \)", "\( ٢ \)", "\( ٣ \)", "\( ٥ \)"], correctAnswer: 0, explanation: "أول الأعداد الأولية تشمل \( ٢ \) و٥. عند ضرب \( ٢ \times ٥ = ١٠ \)، وأي عدد يُضرب في \( ١٠ \) رقم آحاده صفر.", category: "EXAM_2025" },
  { question: "قارن بين: القيمة الأولى: \( ٤^{٥} | \) القيمة الثانية: \( ٤ \times ٤ \times ٤ \times ٤ \times ٤ \)", options: ["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"], correctAnswer: 2, explanation: "المقدار (\( ٤ \times ٤ \times ٤ \times ٤ \times ٤ \)) يساوي تماماً \( ٤^{٥} \)، فالقيمتان متساويتان.", category: "EXAM_2025" },
  { question: "نادي به \( ٥٠ \) مشترك، \( ٣٠ \) منهم مشتركين في كرة القدم و٢٦ مشتركين في السباحة و٦ غير مشتركين في أي منهما، كم عدد المشتركين في كليهما معاً؟", options: ["\( ٠ \)", "\( ٦ \)", "\( ١٢ \)", "\( ٤ \)"], correctAnswer: 2, explanation: "عدد المشتركين في أي منهما \( = ٥٠ - ٦ = ٤٤ \). مجموع المشتركين \( = ٣٠ + ٢٦ = ٥٦ \). التقاطع \( = ٥٦ - ٤٤ = ١٢ \).", category: "EXAM_2025" },
  { question: "مجموع ثلاثة أعداد يساوي \( ٩٦ \)، والأكبر ثلاثة أضعاف الصغير والأوسط ثلثا الكبير. ما الصغير؟", options: ["\( ١٦ \)", "\( ١٢ \)", "\( ١٤ \)", "\( ١٨ \)"], correctAnswer: 0, explanation: "نفرض الصغير \( س \)، الأكبر \( ٣س \)، الأوسط \( ٢س \). مجموعهم: \( ٦س = ٩٦ \leftarrow س = ١٦ \).", category: "EXAM_2025" },
  { question: "ما العدد الذي سدسه يساوي \( \frac{٢٥}{٣} \)؟", options: ["\( ٣٠ \)", "\( ٤٠ \)", "\( ٥٠ \)", "\( ٦٠ \)"], correctAnswer: 2, explanation: "(\( \frac{١}{٦}) \times س = \frac{٢٥}{٣} \leftarrow س = (٢٥ \times ٦) / ٣ = ٥٠ \).", category: "EXAM_2025" },
  { question: "كم كلمة يمكن أن نكوّنها من حروف اسم (خالد)؟", options: ["\( ٤ \)", "\( ٨ \)", "\( ٢٤ \)", "\( ٣٢ \)"], correctAnswer: 2, explanation: "اسم (خالد) يتكون من \( ٤ \) حروف مختلفة. عدد الترتيبات \( = ٤! = ٢٤ \) كلمة.", category: "EXAM_2025" },
  { question: "إذا كان مصاريف مدرسة \( ١٠٠٠٠ \) ريال وزادت \( ٢٠\text{٪} \) ويوجد خصم \( ٥\text{٪} \) للطلاب الأخوة، كم المصاريف التي يدفعها \( أب \) لولدين؟", options: ["\( ٢٤٠٠٠ \)", "\( ٢٢٨٠٠ \)", "\( ٢٣٠٠٠ \)", "\( ٢٢٧٥٠ \)"], correctAnswer: 1, explanation: "المصاريف بعد الزيادة \( = ١٢٠٠٠ \). للولدين \( = ٢٤٠٠٠ \). الخصم \( ٥\text{٪} = ١٢٠٠ \). المبلغ \( = ٢٤٠٠٠ - ١٢٠٠ = ٢٢٨٠٠ \).", category: "EXAM_2025" },
  { question: "\( دفع \) أحمد \( ٤٥\text{٪} \) من تكلفة بناء \( مسجد \) وفهد \( دفع ٢٥\text{٪} \) وتبقى \( ٣٦٠٠٠٠ \). ما تكلفة المسجد كاملة؟", options: ["\( ١٢٠٠٠٠٠ \)", "\( ٣٦٠٠٠٠ \)", "\( ٢٤٠٠٠٠ \)", "\( ١٠٠٠٠٠٠ \)"], correctAnswer: 0, explanation: "المدفوع \( = ٧٠\text{٪} \)، المتبقي \( = ٣٠\text{٪} = ٣٦٠٠٠٠ \). إذن التكلفة \( = ٣٦٠٠٠٠ \times \frac{١٠٠}{٣٠} = ١٢٠٠٠٠٠ \) ريال.", category: "EXAM_2025" },
  { question: "إذا كان طول أحمد \( ١٢٠ \) سم وهو أقصر من أخيه محمد بـ \( ٢٠ \) سم وأقصر من أخته سعاد بـ \( ٥ \) سم، فما مجموع أطوال الثلاثة؟", options: ["\( ٢٥٠ \)", "\( ٣٥٨ \)", "\( ٢٧٠ \)", "\( ٣٨٥ \)"], correctAnswer: 3, explanation: "طول أحمد \( = ١٢٠ \)، محمد \( = ١٤٠ \)، سعاد \( = ١٢٥ \). المجموع \( = ١٢٠ + ١٤٠ + ١٢٥ = ٣٨٥ \) سم.", category: "EXAM_2025" },
  { question: "يبيع تاجر سلعة بربح يساوي نصف مبلغ الشراء. ما أقصى نسبة تخفيض تضمن له \( عدم \) الخسارة؟", options: ["\( ٣٣\text{٪} \)", "\( ٥٠\text{٪} \)", "\( ٦٦\text{٪} \)", "\( ٧٠\text{٪} \)"], correctAnswer: 0, explanation: "بفرض الشراء \( ١٠٠ \)، البيع \( = ١٥٠ \). الحد الأقصى للتخفيض \( = \frac{٥٠}{١٥٠} \times ١٠٠ = ٣٣.٣\text{٪} \).", category: "EXAM_2025" },
  { question: "اشترى شخص عصيراً بـ \( ٦ \) ريالات وهي تمثل \( ٢٠\text{٪} \) مما معه. كم كان معه؟", options: ["\( ٢٠ \)", "\( ٢٥ \)", "\( ٣٠ \)", "\( ٣٥ \)"], correctAnswer: 2, explanation: "\( ٢٠\text{٪} = \frac{١}{٥} \). المبلغ الإجمالي \( = ٦ \times ٥ = ٣٠ \) ريال.", category: "EXAM_2025" },
  { question: "أحمد وخالد مجموع كتبهم \( ٨٥٠ \) وخالد يزيد عن أحمد بمقدار \( ١٥٠ \). كم عدد كتب أحمد؟", options: ["\( ١٠٠ \)", "\( ٢٥٠ \)", "\( ٣٥٠ \)", "\( ٤٠٠ \)"], correctAnswer: 2, explanation: "نطرح الزيادة: \( ٨٥٠ - ١٥٠ = ٧٠٠ \). نصيب أحمد \( = ٧٠٠ \div ٢ = ٣٥٠ \) كتاباً.", category: "EXAM_2025" },
  { question: "وُزّعت \( ٦٤ \) طابعة و٤٨ حاسبة على غرف بالتساوي. ما أكبر عدد طابعات وحاسبات في كل غرفة؟", options: ["\( ٨ \)", "\( ١٢ \)", "\( ١٦ \)", "\( ٢٤ \)"], correctAnswer: 2, explanation: "القاسم المشترك الأكبر للعددين \( ٦٤ \) و٤٨ هو \( ١٦ \).", category: "EXAM_2025" },
  { question: "تحرك شخص \( ٩٠م \) شرقاً ثم \( ١٢٠م \) جنوباً. ما المسافة المستقيمة بين نقطة البداية والنهاية؟", options: ["\( ١٠٠ \)", "\( ١٢٠ \)", "\( ١٥٠ \)", "\( ١٨٠ \)"], correctAnswer: 2, explanation: "بنظرية فيثاغورس: \( \sqrt{٩٠^{٢} + ١٢٠^{٢}} = \sqrt{٨١٠٠ + ١٤٤٠٠} = \sqrt{٢٢٥٠٠} = ١٥٠ \) م.", category: "EXAM_2025" },
  { question: "إذا كان متوسط درجات \( فصل ٨٥ \) قبل اختبار طالب غائب، وبعد اختباره حصل على \( ٣٠ \) وأصبح المتوسط \( ٨٠ \)، فما عدد الطلاب؟", options: ["\( ٩ \)", "\( ١٠ \)", "\( ١١ \)", "\( ١٢ \)"], correctAnswer: 2, explanation: "الفارق في المتوسط \( = ٥ \) درجات. الفارق الكلي \( بسبب \) الطالب \( = ٨٥ - ٣٠ = ٥٥ \). عدد الطلاب \( = ٥٥ \div ٥ = ١١ \) طالباً.", category: "EXAM_2025" },
];

const examQuickQuestions: Q[] = [
  { question: "حل المعادلة: \( ٤س - ٩ = ٣س + ٥ \)", options: ["\( ١١ \)", "\( ١٤ \)", "\( ١٣ \)", "\( ١٢ \)"], correctAnswer: 1, explanation: "ننقل الحدود: \( ٤س - ٣س = ٥ + ٩ \leftarrow س = ١٤ \).", category: "EXAM_QUICK", difficulty: "EASY" },
  { question: "ما قيمة \( ٤٠\text{٪} \) من \( ٢٥٠ \)؟", options: ["\( ١٠٠ \)", "\( ٩٠ \)", "\( ٨٠ \)", "\( ١٢٠ \)"], correctAnswer: 0, explanation: "\( ٢٥٠ \times ٠.٤ = ١٠٠ \).", category: "EXAM_QUICK", difficulty: "EASY" },
  { question: "مستطيل طوله \( ٨ \) سم وعرضه \( ٥ \) سم. ما مساحته؟", options: ["\( ٢٦ \)", "\( ٣٠ \)", "\( ٤٥ \)", "\( ٤٠ \)"], correctAnswer: 3, explanation: "المساحة \( = \) الطول \( \times \) العرض \( = ٨ \times ٥ = ٤٠ \) سم².", category: "EXAM_QUICK", difficulty: "MEDIUM" },
  { question: "سيارة تقطع \( ٢٤٠ \) كم في \( ٣ \) ساعات. كم تقطع في \( ٥ \) ساعات؟", options: ["\( ٣٠٠ \)", "\( ٤٥٠ \)", "\( ٥٠٠ \)", "\( ٤٠٠ \)"], correctAnswer: 3, explanation: "السرعة \( = ٢٤٠ \div ٣ = ٨٠ كم/س \)، إذن المسافة \( = ٨٠ \times ٥ = ٤٠٠ \) كم.", category: "EXAM_QUICK", difficulty: "MEDIUM" },
  { question: "في مثلث زاويتان \( ٦٠^\circ \) و٧٠°. ما قياس الزاوية الثالثة؟", options: ["\( ٧٠^\circ \)", "\( ٦٠^\circ \)", "\( ٥٠^\circ \)", "\( ٨٠^\circ \)"], correctAnswer: 2, explanation: "الزاوية الثالثة \( = ١٨٠^\circ - (٦٠^\circ + ٧٠^\circ) = ٥٠^\circ \).", category: "EXAM_QUICK", difficulty: "EASY" },
];

async function main() {
  console.log("🌱 Seeding questions...");

  await pool.query(`DELETE FROM "Attempt"`);
  await pool.query(`DELETE FROM "Question"`);

  const all = [
    ...algebraQuestions,
    ...geometryQuestions,
    ...numbersQuestions,
    ...probabilityQuestions,
    ...patternsQuestions,
    ...ratioQuestions,
    ...exam2025Questions,
    ...examQuickQuestions,
  ];

  for (const q of all) {
    await pool.query(
      `INSERT INTO "Question" (id, category, question, options, "correctAnswer", explanation, difficulty, "createdAt")
       VALUES (gen_random_uuid(), $1, $2, $3::jsonb, $4, $5, $6, NOW())`,
      [q.category, q.question, JSON.stringify(q.options), q.correctAnswer, q.explanation, q.difficulty ?? "MEDIUM"]
    );
  }

  // Set admin user
  await pool.query(
    `UPDATE "User" SET "isAdmin" = true WHERE email = $1`,
    ["marie.benbekhti@gmail.com"]
  );
  console.log("✅ Admin user set.");

  console.log(`✅ Seeded ${all.length} questions successfully!`);
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
